### ISSUE TITLE
Relax the `fileType` function to permit Monaco (and ACE) to work with more file types

### ISSUE THREAD

**Issue by Steve-Mcl** [TotallyInformation/node-red-contrib-uibuilder#102]
Software       | Version
-------------- | -------
Node.JS        | All
npm            | NA
Node-RED       | ALL
uibuilder node | 3.0.0
OS             | All
Browser        | All

Hi Julian, as discussed [here](https://discourse.nodered.org/t/using-monaco-editor-monaco-branch-now-in-fork-pr-2798/26561/108?u=steve-mcl), is it possible you can relax the `fileType` function to permit Monaco (and ACE) to work with more file types?

**Comment by TotallyInformation** [comment]
The function that does the work is here:

https://github.com/TotallyInformation/node-red-contrib-uibuilder/blob/35453e6ea2a7b77f95b30c45aaa8173e264f9b47/nodes/uibuilder.html#L185-L218

I will change the default entry to return the `fext` value rather than 'text'.

Assuming that doesn't create any issues, it will be incorporated into the next release.

**Comment by TotallyInformation** [comment]
Fixed.

Minor issue remains that you can "edit" binary files like images - I probably should stop that :-)

Also note that this change highlighted a couple of small bugs related to trying to edit dotfiles. Now also fixed. See #105 and #106
