### ISSUE TITLE
package manager install in the wrong place

### ISSUE THREAD

**Issue by tve** [TotallyInformation/node-red-contrib-uibuilder#127]
I'm using a docker install of NR and when I use the uibuilder package manager to install packages they end up in `<httpRoot>/node_modules` instead of `<userDir>/node_modules`. IMHO this is incorrect?

In order to serve up the packages as `/uibuilder/vendor/<packageName>/...` I need to make `<userDir>/node_modules` a symlink to `<httpRoot>/node_modules`. Specifically, `/data/node_modules` -> `/usr/src/node-red/node_modules`.

### Software and Package Versions

> Node.JS, Node-RED and uibuilder back-end versions are listed in the Node-RED log on startup. 

uibuilder 3.2.0

> Please also include your Operating System name and version and your browser's name and version.
Linux, latest Chrome

> I know it seems like a lot but it saves time in the long run

Software       | Version
-------------- | -------
Node.JS        | 
npm            | 
Node-RED       | 
uibuilder node | 
uibuilderFE    | 
OS             | 
Browser        | 

### How is Node-RED installed? Where is uibuilder installed?

Docker install

**Comment by TotallyInformation** [comment]
Hmm, that shouldn't happen. uibuilder uses the RED.settings API to get the userDir. If you open the details page from any uibuilder node, you can see what it thinks is the setting:

![image](https://user-images.githubusercontent.com/1591850/116441517-6d042800-a849-11eb-8d88-5b39e8ef7d68.png)

**Comment by tve** [comment]
Hmm, it looks to me like there's some confusion. I know of three pathnames:
- there's the HTTP path to reach the node-red top-level page, in my case it's `/` for `http://localhost:1880/`, looks like this is what you call `httpNodeRoot`
- there's the filesystem directory that contains the files served up by node-red via http, in my case it's `/data` (std when using the docker container), and in `/data` I have files like `/data/uibuilder/uib_simple/src/index.html`
- there's the node-red filesystem home directory or current working directory, which is where the `node_modules` is located from which the Node-Red process loads all its modules, in my case that's `/usr/src/node-red` (std when using docker container)

Looking at the Node-Red log, it says `User directory : /data`, so that's `userDir`. The issue are:
- the package manager installs into `/data/node_modules` when all modules for node-red are in `/usr/src/node-red/node_modules`
- paths like `/uibuilder/vendor/<package>/...` look into `/data/node_modules/<package>/...` when all modules for node-red are installed in `/usr/src/node-red/node_modules`

IMHO when uibuilder deals with npm packages it should put them into or fetch them from the processe's node_modules directory, not from some directory related to userDir or http. Otherwise we end up with another whole node_modules tree in userDir. Or perhaps I'm wrong, and creating a new node_modules tree in userDir is the right way to go, but then one has to start off with installing node-red-contrib-uibuilder there.

**Comment by TotallyInformation** [comment]
Please note that in every case both in code and the documentation, a URL is said to have a "path" and the filing system a "folder". This is to help avoid confusion. In the documentation, you will see that I often use references such as `<uibRoot>` which is the folder that contains everything that is specific to uibuilder. This is because, due to the way Node-RED works and its flexibility, I can never be certain where _your_ folders actually are.

> the package manager installs into /data/node_modules when all modules for node-red are in /usr/src/node-red/node_modules

This is not my fault, it is the way that docker has been set up. In fact, this is perfectly acceptable and you shouldn't have any issues with that and uibuilder. With node packages stored in that location, you wouldn't normally be able to maintain them as a user nor from within the Node-RED package manager. Because a user won't have write access to that location.

That doesn't stop you also installing nodes into the userDir which is the normal location. uibuilder also uses the userDir folder to install packages. Since the uibRoot folder is underneath the userDir, everything will still work.

> paths like /uibuilder/vendor/<package>/... look into /data/node_modules/<package>/... when all modules for node-red are installed in /usr/src/node-red/node_modules

This has no real bearing on the matter since uibuilder does not have to rely on any other nodes other than itself. If you install, lets say, jQuery into the `/data` folder, uibuilder will be perfectly happy.

> MHO when uibuilder deals with npm packages it should put them into or fetch them from the processe's node_modules directory, not from some directory related to userDir or http. Otherwise we end up with another whole node_modules tree in userDir. Or perhaps I'm wrong, and creating a new node_modules tree in userDir is the right way to go, but then one has to start off with installing node-red-contrib-uibuilder there.

I don't think this is quite correct. It is a consequence of installing everything into Node-RED's root instead of the users root. As I say, this is not normal even though it is allowed.

In fact, in the case you outline, you would want all of uibuilders packages to be installed into `/usr/src/node-red` but that is absolutely wrong. That folder should only be writable via sudo and you certainly won't want to be forced to use sudo every time you want to install a front-end library will you?

I will restate that - you are only getting another tree because your docker installation has put the nodes somewhere different. I can't help that. That is not the normal location for nodes.

What's more is that, with the latest release of Node-RED, there is yet another location that can hold packages and that is `userDir>/externalModules`.

The front-end library packages for use with uibuilder have to go somewhere. The best place is the closest parent folder to the uibRoot folder where normally everything else also goes. I can't see any other logical location though I'm open to further suggestions.

**Comment by tve** [comment]
Well, I'm not sure what the correct solution is either, I find node-red's paths and folders somewhat confusing...

The one thing I want to point out is that I'm using the official node-red docker container and the official way it sets up paths/folders, so I'm not some rogue guy with some weird config. I do not believe that uibuilder "just works" with the docker container: surgery is required, at least that was my experience. You may not care, and perhaps the docker deployment method is to be considered fringe, I don't know.

**Comment by TotallyInformation** [comment]
> The one thing I want to point out is that I'm using the official node-red docker container and the official way it sets up paths/folders, so I'm not some rogue guy with some weird config.

Sorry, didn't mean to imply that. I realise you are using the official Docker package. It's just odd that it is set up that way. Presumably because of something to do with the way that Docker does things.

> You may not care, and perhaps the docker deployment method is to be considered fringe, I don't know.

I most certainly do care. uibuilder is meant to be universal and completely flexible.

What I'm still struggling with is what is going wrong. I can't see any reason as yet why uibuilder shouldn't still work perfectly with the docker configuration since all that you've pointed out so far is that when you use it and install nodes, they get installed into the global location instead of the userDir location. This should make no difference at all to uibuilder as long as the userDir folder location is accessible and the uibRoot folder is contained withing the userDir.

You may have seen that the ability to move a specific uibuider instances root folder is on the backlog. But I don't think this helps here.

Can you please list here or send in a PM on the forum the output from the details page as requested further up? It may well provide more clues.

I am also surprised that nobody else has reported this since the use of Docker with Node-RED is far from unusual.

**Comment by tve** [comment]
I tested things with a clean install and they work! Sorry for the noise!
What's a bit confusing is that after installing vuetify in the package manager it's in userDir/node_modules whereas bootstrap-vue, if installed through the template initialization stuff is in ~/.node_red/node_modules, but they all get served up correctly
