### ISSUE TITLE
uibuilder doesn't support subdirectories

### ISSUE THREAD

**Issue by tve** [TotallyInformation/node-red-contrib-uibuilder#128]
uibuilder version 3.2.1

The uibuilder examples all create pages at `/foo` by setting the URL property of the uibuilder node to `foo`. It would be really nice if one could use a path there, not just a single flat name. For example, I'd like to use `dashboard/home`, `dashboard/greenhouse`, etc. This fails in a number of ways:
- the `uibuilderfe.js` does not construct the correct `ioPath` and fails to connect the socket.io, this can be worked around by passing the correct path into `uibuilder.start()`
- the "edit files" and "manage front-end libraries" buttons on the uibuilder node cease to function

**Comment by TotallyInformation** [comment]
Hi, thanks for raising this.

There are a variety of reasons this is so. Not least the difficulty of the front-end "knowing" where the back-end is, specifically the Socket.IO connection. The uibuilderfe code uses several techniques to try and find or guess this but it can never be 100%.

Also, if a non-flat url name was used, it would massively complicate the file system handling on the Node-RED side for really very little reward.

This is why the start command allows the override parameters. So that you can have sub-folders of the main URL and can even serve up your front-end pages from a completely different server if you like.

---

Having said that, if you have any ideas for improving this situation, I am more than happy to listen 😎

**Comment by tve** [comment]
So the override params on start work, but the buttons in the uibuilder node are broken and I don't really get why they can't append the full pathname from the URL...

**Comment by TotallyInformation** [comment]
It is possible that uibuilder could be extended to allow sub-paths on the URL. However, the path handling is already very complex and doing so would likely break various things that would then all have to be fixed. At the least, it would require copious amounts of testing.

I'm open to a pull request.  

If you've seen my project board and the larger to do list in the WIKI, I'm afraid that this is something that isn't on my radar right now. Sorry.

**Comment by tve** [comment]
I've reverted my stuff to use `d-foo` instead of `d/foo`. WOuld be nice to support pathnames at some point, but I understand the priorities...
