### ISSUE TITLE
http://ccu3-webui/addons/red/uibindex gives ERR_INVALID_URL

### ISSUE THREAD

**Issue by simonbuehler** [TotallyInformation/node-red-contrib-uibuilder#143]
hi,
i get `TypeError [ERR_INVALID_URL]: Invalid URL: undefined` when trying to access uibuilder- or instance details. see attached debug logfile, any idea how to fix?

[redmatic.2021-06-25T09_01_29.058Z.log](https://github.com/TotallyInformation/node-red-contrib-uibuilder/files/6714990/redmatic.2021-06-25T09_01_29.058Z.log)

**Comment by TotallyInformation** [comment]
There is a LOT going on there that I have no idea about since it seems to be redmatic specific, you will need a redmatic forum to help maybe?

```
Jun 25 10:54:23 ccu3-webui daemon.debug node-red[6145]: uibuilder : admin : URL . . . . .  : /addons/red/admin
Jun 25 10:54:23 ccu3-webui daemon.debug node-red[6145]: uibuilder : admin : Source files . : /usr/local/addons/redmatic/var/uibuilder/admin
Jun 25 10:54:23 ccu3-webui daemon.debug node-red[6145]: uibuilder : dash : URL . . . . .  : /addons/red/dash
Jun 25 10:54:23 ccu3-webui daemon.debug node-red[6145]: uibuilder : dash : Source files . : /usr/local/addons/redmatic/var/uibuilder/dash
```

I don't recognise any of that, what is it?

```
Jun 25 10:58:16 ccu3-webui daemon.err node-red: TypeError [ERR_INVALID_URL]: Invalid URL: undefined
Jun 25 10:58:16 ccu3-webui daemon.err node-red:     at onParseError (internal/url.js:259:9)
Jun 25 10:58:16 ccu3-webui daemon.err node-red:     at new URL (internal/url.js:335:5)
Jun 25 10:58:16 ccu3-webui daemon.err node-red:     at /usr/local/addons/redmatic/var/node_modules/node-red-contrib-uibuilder/nodes/uibuilder.js:993:21
```

I have no idea what `internal/url.js` is - is that something to do with redmatic? I appears to be referencing the link to uibIndex page

![image](https://user-images.githubusercontent.com/1591850/123548486-d70f4f80-d75c-11eb-9366-3416f6d9a594.png)
![image](https://user-images.githubusercontent.com/1591850/123548520-f312f100-d75c-11eb-8364-74ba5860d52f.png)

As this works normally, I can only assume that something redmatic is doing is interfering with the call.

https://github.com/TotallyInformation/node-red-contrib-uibuilder/blob/v3.3.1/nodes/uibuilder.js#L993

![image](https://user-images.githubusercontent.com/1591850/123548570-2eadbb00-d75d-11eb-9af4-41f0f7da0fa4.png)

**Comment by simonbuehler** [comment]
thanks for the feedback, will redirect this issue to redmatic / uibuilder, thanks for having a look!

**Comment by simonbuehler** [comment]
the admin / dash pages are two i setup with uibuilder as  frontend/ backend status display
