### ISSUE TITLE
Issue using built in security button

### ISSUE THREAD

**Issue by adamz0210** [TotallyInformation/node-red-contrib-uibuilder#148]
![https error](https://user-images.githubusercontent.com/64041152/126578639-ec5d2da7-486f-4254-9f21-173889ea103b.jpg)

Hi,

I am attempting to enable the checkbox for the built-in security feature but it doesn't seem to let me enable it. 
I read through your docs and enabled tls so node-red is running using https, but it still wasn't allowing me to check the box. So I opened up the chrome developer tools and saw the error "HTTPS NOT IN USE BUT SECURITY REQUESTED AND Node environment is NOT "development"". I found in your code that you are checking the protocol by running window.location.protocol, so I ran that in my console and got "https:" as seen in the screenshot above.

I think that no matter what situation I will be sucked into the if statement posted below because one of those statements will always be true. Maybe changing that line to " if (!window.location.protocol.includes("https")) { "

Uibuilder is an amazing node and I want to have full functionality of it. Please let me know if I'm misunderstanding the issue and how I can solve it if I am. Thanks!

https://github.com/TotallyInformation/node-red-contrib-uibuilder/blob/f798bc076c6961a7207a40439e18c261323082a2/nodes/uibuilder.html#L1007

**Comment by TotallyInformation** [comment]
Hi Adam.

Ah, logic failure in developer wetware is causing this issue!

That line should, of course have an AND not an OR between the two statements. Doh.

I will fix and publish as v4.1.0 (along with a nice couple of new features that I had already added to sweeten the deal!)

**Comment by samhuss** [comment]
Hi, 
First thank you @TotallyInformation  for the great work, I'm using uibuilder with svelte and routify and the result is amazing. 
However, It took me a while to reach this issue while trying to enable the 'use security' checkbox which should be documented in the docs. All I see in the docs is enabling TLS is a must, while this statement can be resolved when running behind reverse proxy with valid certificate behind https, so there was no clue that TLS must still be enabled in node-red itself. 

I'm still don't see a valid point of enabling TLS in node-red while the request is done through the https request from the browser, the point of enabling https is to have a secure link between the browser and the first entry point of the backend, which in this case is the proxy or the gateway, after passing the proxy, all the communication is done internally in a secure environment using http, and that's why all the reverse proxies are supporting SSL offload. 

Please if possible to remove the extra check for the handshake between uibuilder `node` and the browser as mostly and in my case node-red will be hosted inside Kubernetes behind a GW and in other environment behind reverse proxy with https certificate, so no way uibuilder will have receive a https  handshake. 

Even if I enabled TLS on node-red in a secure environment, it will be done with a self-signed certificate as the reverse proxy has another signed certificate with the actual domain. 

BTW, just to give an example, what I'm saying is implemented in most of the OAuth tools like Keycloak which is meant to run in a very secure environment, it supports http and https depending on the runtime environment, so most of the time in my work I host it behind a secure GW with a signed certificate that offloads all the cluster SSL calls.

**Comment by TotallyInformation** [comment]
Hi Sam. Yes, I saw this issue as well having messed with some reverse proxy stuff on NGINX and Caddy. Rest assured that the block will shortly be removed but the warning will remain.

The docs do, I believe though, make it absolutely clear that you have to enable TLS for production use. But they don't make it clear that a reverse proxy isn't enough.

As you've reminded me, I've also added this to the next column on the project board.

https://github.com/TotallyInformation/node-red-contrib-uibuilder/projects/1?fullscreen=true

I will try to make the documentation clearer as well.
