### ISSUE TITLE
Remove block for no TLS on production since TLS could be provided by a reverse proxy and not Node-RED itself.

### ISSUE THREAD

**Issue by TotallyInformation** [TotallyInformation/node-red-contrib-uibuilder#149]

**Comment by samhuss** [comment]
Great, thanks for the fix

**Comment by nauben** [comment]
Hi,
as I understand, uibuilder's built in security should not require TLS now right? 
However, in the logon-function in nodes/libs/uiblib.js a secured socket is still necessary: 
`// Check if using TLS - if not, send warning to log & inform client and exit
        if ( socket.handshake.secure !== true ) {`
So instead of exiting, can just a warning be displayed instead? Could you please check?

**Comment by TotallyInformation** [comment]
Hi, that can be changed, yes. I will try and change it shortly.

However, please note that uibuilder v5 (currently available for testing as the vNext branch here on GitHub) is removing the security features as these have never been robust or production ready and they are constantly getting in the way of other improvements. I will probably leave in a stub for the logon/logoff control messages though so that you can handle things via custom Socket.IO and ExpressJS middleware functions.

I will revisit security in a future release and if you have any suggestions, please do let me know. I am trying to work up an example NGINX reverse proxy example that will demonstrate how to use it for security.
