### ISSUE TITLE
A question about 'this' in uibuilder function

### ISSUE THREAD

**Issue by colinl** [TotallyInformation/node-red-contrib-uibuilder#16]
At the start of uibuilderfe.js is the code
`const uibuilder = function () {
    const self = this;`
I am not sure what 'this' is referring to, the code won't run after I feed it through babel.
When I examine this (running without babel) in the console it has the value
`Window → http://<ip>:1880/home/`
Having run the code through babel 'this' shows as undefined.

**Comment by TotallyInformation** [comment]
Hmm, unexpected! The uibuilder object is a self-executing function that contains multiple attributes and methods. The reference to `this` at the start ensures that we have a consistent reference since the value of `this` will change for any callback functions which, of course, we are making good use of.

The effect is to isolate much of the code within the root function and only expose what we want via the callback functions listed in the return.

The advantage of this approach is that it works in the browser with no dependencies on a build phase. I have to say that I am surprised that it breaks when using webpack but I'm not really familiar with webpack yet.

**Comment by colinl** [comment]
I am not with you there. As far as I can see there is only one instance of uibuilder. Is it not a global function in the browser? In fact when run (without webpack) this == window, so all the attributes are effectively global objects (within the window).

**Comment by TotallyInformation** [comment]
OK, my bad, the self-executing function doesn't isolate things as much as I thought.

I think that the function needs to change to something like:

```
const me = new (function () {
    const self = this
    self.a = 1
    self.b = 2
    console.dir(self)
    return {
        a: self.a,
        b: self.b
    }
});

console.log(me.a)
console.log(me.b)
```

So I'm doing a "new" against an anonymous function. That seems to do what I need in isolating everything and only exposing the top-level var.

There may be better ways but I can't currently see any better way without *having* to use webpack and I really want to keep that as optional rather than mandatory if I possibly can.

If you can, could you make the change in your local copy of uibuilderfe.js - it is only 2 lines, the first and last of the function definition. Then test with your webpack build? 

I'm still trying to get my head round the right config for building the FE code - I *think* that all that is needed is to minimise `src/uibuilderfe.js` into `dest/uibuilderfe.min.js` - hopefully the updated code will work.

**Comment by TotallyInformation** [comment]
I've pushed an update just to uibuilderfe.js containing the amended function definition.

**Comment by TotallyInformation** [comment]
Grrr. Super-annoying that webpack can't cope with ES6 of any sort without using babel to transcode down to ES5 - massive overkill. So I'm removing all the ES6 from the uibuilderfe.js file for now.

**Comment by TotallyInformation** [comment]
Another issue with webpack. When in minifies, the uibuilder name is also minified so I need to know how to retain that name.

**Comment by colinl** [comment]
I think using exports solves that problem.

**Comment by TotallyInformation** [comment]
Drat! I can't work out the right settings to make uglify keep the uibuilder var name. Don't know if you can work it out. This is what I have at the moment in my webpack.config.js file:

```
/**
 * Webpack Configuration
 */

const UglifyJSPlugin = require('uglifyjs-webpack-plugin')

module.exports = {
    entry: './nodes/src/uibuilderfe.js',
    output: {
        filename: './nodes/dist/uibuilderfe.min.js'
    },
    plugins: [
        new UglifyJSPlugin({
            uglifyOptions: {
                compress: {
                    keep_fnames: true
                },
                mangle: {
                    keep_fnames: true,
                    reserved: ['uibuilder']
                }
            }
        })
    ]
}
```

I'm obviously doing something wrong but I can't work it out and I can't find any suitable examples. I've tried lots of combinations of parameters but nothing works. I've also tried the Google Closure compiler which did highlight a few code and jsdoc issues but still doesn't work.

Seems as though nothing likes my definition line - there must be a better approach than that but I can't see it.

**Comment by colinl** [comment]
I will get mine going with your latest uibuilder.js and I will post my config.

**Comment by colinl** [comment]
The changes in uibuilderfe.js (const uibuilder = new (function () ) has fixed the 'this' problem for me.
On the webpack issue I have taken a different line, I have copied uibuilderfe.js to url/src and included it in the bundle.js. I have also built in jquery and riot so the only js not yet included is socket.io.
To make this work I had to add to the end of uibuilderfe.js

if (typeof module === "object" && module.exports) {
  module.exports = uibuilder
}

and add to the front of index.js
if (typeof require != "undefined") {
  var builder = require('./uibuilderfe')
  var riot = require('riot')
  require("./index.css")
  require("./application-tags.tag")
} else {
  var builder = uibuilder
}

Those changes do not affect operation when running from src, except that I have to use the variable builder rather than uibuilder. I could not use var uibuilder=require('./uibuilderfe') As it then objected to the redefinition as uibuilder is defined const.
I have attached my webpack.config.js - or at least I tried but it won't seem to let me attach a js file so pasting it below instead.
I suspect that adding the exports may help with the problem you are seeing but not certain. It might allow the name to be accessed externally.
From my point of view the ideal would be to have the exports added to uibuilderfe.js and to work out how to get webpack pick up uibuilderfe.js from the node, rather than having to copy it to src, but I have so far failed to manage that.

webpack.config.js:
var webpack = require('webpack')
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const UglifyJSPlugin = require('uglifyjs-webpack-plugin');
const path = require('path');

var HTMLWebpackPluginConfig = new HtmlWebpackPlugin({
  template: __dirname + '/uibuilder/home/src/index_template.html',
  filename: 'index.html'
});

var CopyWebpackPluginConfig = new CopyWebpackPlugin([
  { from: './uibuilder/home/src/images/node-blue.ico' },
  { from: './uibuilder/home/src/manifest.json' }
]);

module.exports = {
  entry: [
    './uibuilder/home/src/index.js'
  ],
  output: {
      path: path.resolve(__dirname, 'uibuilder/home/dist'),
      filename: 'bundle.min.js'
  },
  plugins: [
    new UglifyJSPlugin({
      compress: {
        warnings: true
      }
    }),
    HTMLWebpackPluginConfig,
    CopyWebpackPluginConfig,
    new webpack.ProvidePlugin({
        $: "jquery",
        jQuery: "jquery"
    })
  ],
  module: {
    loaders: [
      {
        test: /.js$/,
        loader: 'babel-loader',
        query: {
          presets: ['env']
        },
        exclude: /node_modules/
      },
      {
        //test: /uibuilder\/home\/*\.tag$/,
        test: /\.tag$/,
        exclude: /node_modules/,
        loader: 'riot-tag-loader',
        query: {
          hot: false, // set it to true if you are using hmr
          // add here all the other riot-compiler options riotjs.com/guide/compiler/
          // template: 'pug' for example
        }
      },
      {
        test: /\.css$/,
        exclude: /node_modules/,
        loader: 'style-loader!css-loader'
      }
    ]
  }
};

**Comment by TotallyInformation** [comment]
Thanks for that, I will see what I can do. I'm going to try to see if I can wrap the details in an IIFE and pass in the uibuilder var as a parameter so that is the only thing that is exposed. Along with your export stuff, hopefully that will resolve it all.

I'm not entirely convinced by bundling uibuilderfe with jquery as the that is not always needed (if using Moon or Riot for example). Does it really make that much difference. In any case, if you need to run webpack on uibuilderfe yourself, you will have to copy it I'm afraid though you don't have to put it in url/src, you can put it anywhere that you can get to when you run webpack, you just need to change the entry point.

I'm also wondering whether it wouldn't be better to switch JQuery for one of the lighter equivalents - *what do you think*?

I'm also going to set up a slack channel. I'm just seeing whether Nick would be happy to host it on the Node-RED slack, otherwise I'll set it up on my own.

**Comment by TotallyInformation** [comment]
Actually, I think we need to remember that we are trying to do slightly different things. All I'm trying to do at the moment is to minimise uibuilderfe.js and give that as an option to use.

What you are trying to do is much more by bundling up everything. I see that as a user task as opposed to my dev task. Eventually, I want to be able to offer users of uibuilder the option to automatically bundle their own front-end code from within Node-RED without having to know lots about webpack, etc. The ideal is to make creating a fully custom ui as easy as possible. So that users only need to know the basics of html/css/javascript but can still build something optimal without losing the ability to continue to customise as they gain more knowledge and experience.

Well, that's the goal anyway, we'll see how that pans out - probably going to take quite a while to achieve as I still need to work out how to let people easily insert code from Node-RED without having to resort to the filing system.

By the way, if you've any ideas on those fronts, please feel free to take to the WIKI to jot them down :-)

**Comment by TotallyInformation** [comment]
Looks like this may hold all the answers actually: http://www.richardrodger.com/2013/09/27/how-to-make-simple-node-js-modules-work-in-the-browser/

**Comment by TotallyInformation** [comment]
Hi Colin, can we take the discussion to Slack?

https://node-red.slack.com

then join the uibuilder channel

**Comment by colinl** [comment]
I haven't used slack. It says I need to contact the workspace admin for an invitation.

**Comment by TotallyInformation** [comment]
That's fine, I think that you just fill in the details, I used my GitHub account, it should let you in I think. Been a while since I did it.

**Comment by TotallyInformation** [comment]
Or maybe I signed up with my GitHub account first and then joined the node-red group.

**Comment by colinl** [comment]
Found it, I think, you posted the wrong url, it is https://nodered.org/slack/

**Comment by TotallyInformation** [comment]
OK, I just posted the url I was in at the time.

**Comment by TotallyInformation** [comment]
Hopefully the last change has been pushed for this.

Everything in `uibuilderfe.js` is now wrapped to isolate the code.

I was using `var uibuilder = new (function(){})` but that didn't seem right (line 74 of uibuilderfe.js) - it should, of course, be `var uibuilder = (function(){}).call(root)` which is what it now is.

Also webpack dropped for now and simply using uglifyjs to minimise. Seems to be working fine.
