### ISSUE TITLE
Missing vue.js file

### ISSUE THREAD

**Issue by Smyl3** [TotallyInformation/node-red-contrib-uibuilder#171]
Hi,
I installed newest node from Node-red builtin palette manager.
If I pull the node to a flow and install Vue, bootstrap-vue from the node's library manager and set Template to use VueJS, the uibuilder web page shows a blank page.
The pages says:
Template: Simple VueJS = missing file: vue.js 404
Template: VueJS & bootstrap-vue = missing file: vue.js 404

uibuilder URL = ../uibuilder/vendor/vue
Browser Entry Point (est.) = ../uibuilder/vendor/vue/dist/vue.global.js
Server Filing System Folder = /data/node_modules/vue

Software       | Version
-------------- | -------
Node.JS        |  v14.18.2
npm            |  6.14.15
Node-RED       |  v2.2.1
uibuilder node | 4.1.4
uibuilderFE    | 
OS             | Dietpi, Docker
Browser        |  Opera, Vivaldi, Edge

I tried it on 2 different raspberry with newly installed Node-Red container.

**Comment by TotallyInformation** [comment]
Can you please share the index.html or at least the part where you load Vue?

It should look like:

```js
<script src="../uibuilder/vendor/vue/dist/vue.js"></script>
```

There are various .js files available in Vue's dist folder. They all do slightly different things. The example above is the development version of Vue which is useful when you are developing as it gives you access to the Vue dev tools extension. The Vue npmjs.org page tells you which files are which.

**Comment by Smyl3** [comment]
Sure. I have this on the end of the html body tag:

    

    
    <script src="../uibuilder/vendor/socket.io/socket.io.js"></script>

    
    <script src="../uibuilder/vendor/vue/dist/vue.js"></script> 
    
    
    <script src="../uibuilder/vendor/bootstrap-vue/dist/bootstrap-vue.js"></script> 
    

    
    <script src="./uibuilderfe.js"></script> 
    

    
    <script src="./index.js"></script>

I didn't modify anything nor template html.
uibuilder Detailed Information Page says:
vue package entry point is: vue.global.js in folder: http://192.168.1.10:1880/uibuilder/vendor/vue/dist/vue.global.js
vue.global.js file is existing, I can click on it, but vue.js is not if I modify the url.
There is no vue.js file on server folder: /data/node_modules/vue/dist
If I replace vue.js in html to vue.global.js, still got blank page with following errors in console:
Uncaught TypeError: Vue__default.default.extend is not a function
    at normalize-slot.js:7:39
    at bootstrap-vue.js:14:100
    at bootstrap-vue.js:15:2

Uncaught TypeError: Vue is not a constructor
    at index.js:24:13

**Comment by TotallyInformation** [comment]
Hang on, which version of VueJS is installed? You can check from the command line or look at the package.json file in your userDir folder (normally `~/.node-red`. I'm betting you have v3 installed? The uibuilder templates currently only support v2 I think. 

There is a bit of a mess in the VueJS world at the moment. They've changed the default version to v3 but most Vue-based libraries and extensions still don't support it. It is quite a bit different and will likely take a long time for things to catch up. Until bootstrap-vue switches to Vue v3, I won't be changing the templates in uibuilder unless someone creates some v3 compatible ones as I don't have time to mess with them.

**Comment by Smyl3** [comment]
I found this in Node-red's data folder root package.json:
    "dependencies": {
        "bootstrap-vue": "^2.21.2",
        "node-red-contrib-uibuilder": "~4.1.4",
        "vue": "^3.2.31"

But if I'm right uibuilder node is also installing version 3 VueJS via builtin Front-End Library Manager.
nodered_data/node_modules/vue/package.json contains:
  "_from": "vue@latest",
  "_id": "vue@3.2.31",

So why the node doesn't install to use version 2?
I'm new in uibuilder and VueJS and I would start to use it, but I'm clueless now.

**Comment by TotallyInformation** [comment]
Part of the issue is that Vue recently changed its default from v2 to v3 which is annoying if you don't realise. But obviously, I have no control over that, it is down to the Vue project. I understand why they want to push it but the changes from v2 to v3 are very considerable and it will be a year or two yet before many of the extensions and components catch up. bootstrap-vue itself is a fairly enormous and complex undertaking - it isn't easy for developers to find the time and resources to change over. 

Same for uibuilder - I've looked several times at what needs to change in the Vue templates and I still don't really understand. But even if I did, the dependency on bootstrap-vue for those templates (which makes things sooo much easier for beginners) means that there is little I can do until that project makes the switch as well.

> So why the node doesn't install to use version 2?

Well, if you saw the install log for uibuilder, you would see that it tells you to use Vue v2. Another issue is that trying to install Vue and bootstrap-vue automatically was causing lots of issues and so I had to remove that feature. I've tried various different ways without much success.

In addition, I've been moving away from having front-end library dependencies for uibuilder itself which is why the default template going forwards is "blank".

So uibuilder v4 simply tries to install the current @latest version of a package. When v5 is published, you will be able to pick a version or indeed install from GitHub or anywhere else that `npm` recognises.

One thing this has highlighted is a gap in the template dependency specification though and I will fix that when I get a chance. I also have, on the backlog, a task to develop dependency installation so that you will be able to click a button and uibuilder will do it for you. This is now possible because of the extensive rewrite of the underlying code for v5, previously it wasn't feasible.

> I'm new in uibuilder and VueJS and I would start to use it, but I'm clueless now.

All is not lost. What you need to do is access a command line on the device where Node-RED is running. Then run the following commands:

```bash
cd ~/.node-red
npm remove vue bootstrap-vue
npm install vue@legacy bootstrap-vue@latest
```

Then restart Node-RED and reload the editor page.

---

If you are just getting going with uibuilder, you might instead choose to install the vNext version which eventually will be come v5. To do that, run the following commands:

```bash
cd ~/.node-red
npm install totallyinformation/node-red-contrib-uibuilder#vNext
```

and restart node-red and reload the editor page.

Note however that you will then need to reinstall your libraries. But this time you can use the library manager. Make 2 additions to the libraries in the manager, the first being `vue@legacy` and the second simply being `bootstrap-vue`. No need to restart Node-RED.

**Comment by TotallyInformation** [comment]
v5 allows installation of any version/branch for front-end libraries. This will be closed on deployment of v5.
