### ISSUE TITLE
Understanding `_` filter on listall function

### ISSUE THREAD

**Issue by mlschuh** [TotallyInformation/node-red-contrib-uibuilder#190]
Hi Julian,

I'm working on bringing various wider developer tools to be able to be easily integrated into Node-RED mostly focusing around things that are the last 10% for a lot of production environments. The next on my list is some kind of user manual. I've used Docsify (https://docsify.js.org) before and it is especially appealing because it provides a nice user experience, files written in markdown, and not requiring a build step. I already have it working with UI Builder being the server with one exception: It uses file names that start with `_` as system level files and UI builder seems to hide those from its editor. For example, if you want a sidebar/left menu bar, the file name is `_sidebar.md`. 

I dug into the code and found the `listall` function that returns the file list (https://github.com/TotallyInformation/node-red-contrib-uibuilder/blob/2f533a6716eda9bae57592e0aecf07ac74e95ad7/nodes/libs/admin-api-v3.js#L221) and was wondering about the decision to exclude `_*` files. I'm sure there is a reason you did that but am not sure what it is so don't want to issue a PR without that greater context. If you have thoughts on what might be done (or possibly a different Node-RED node that can act as a file editor?), I'm all ears and can help with the code if you'd like.

-Mitch

**Comment by TotallyInformation** [comment]
Hi, thanks for raising this. The reasoning was to enable a simple way for users to ensure they can exclude files from uibuilder. By common convention, anything starting with a `.` or `_` is considered private. So these are excluded.

I think that if you wanted to have this as an option, it would need to be added to settings.js since that is only available to accounts that have access to the userDir and so is rather more secure.

I'm open to a PR to add that as an option to the uibuilder section of settings.js if you would find that helpful.

**Comment by TotallyInformation** [comment]
Added to the backlog to add a settings.js option. Will appear in a future version though can't say when. More than happy for a PR to be submitted if you like. In the meantime, I'll close this.
