### ISSUE TITLE
Websocket false

### ISSUE THREAD

**Issue by jbperrin88** [TotallyInformation/node-red-contrib-uibuilder#24]
Hi there !

This plugin seems to be nice , but after reading every line of your WIKI , I can't find a way to make it works.

I mean, I only use your default web page to test sending or receiving msg.

Unfortunatly , the websokcet state is false .

I try to disable httpAuth parameter.

![image](https://user-images.githubusercontent.com/11284940/32607544-a2f2aa44-c559-11e7-909e-e9a201a633fd.png)

Do you have an idea ?

Regards

**Comment by TotallyInformation** [comment]
Can you please tell me how you have Node-RED set up and how you are accessing it? What platforms, browser?

If you are using a standard Node-RED setup and can access Node-RED's admin ui - typically http://<ipaddress>:1880/ or similar, then you should be able to run this. Clearly you have a node deployed since you are getting the default page.

Can you also please open your browser's console (F12) and see if there are any errors.

Also, in the uibuilder node settings, you can turn on the front-end debugging. So turn that on and look in the browser console, we should get a better view of what is happening.

**Comment by TotallyInformation** [comment]
Hi, @jbperrin88 - I am going to close this issue. As you haven't come back with more information, I am assuming you got it working. If not, please feel free to reopen the issue with additional information so that we can resolve any problems.

Please also note that there are later versions that the one you are using, the current live version is 1.0.1 and the current build is 1.0.2 (you can install that from GitHub).

We know that uibuilder is now reasonably stable and working on multiple platforms and recent issues have been down to how Node-RED is installed rather than problems with the node. Not to say that you mightn't have found some problem of course.

**Comment by jbperrin88** [comment]
Hi there ,

I'm confused , but I haven't find the time to answer before ....

So I investigate a bit , and i've found a solution.

I force the client to use the non minified version of uibuilderfe.js (in index.html) and it works ...

I don't use the default configuration of node-red.

I mean , i set a HTTPS certificate from my own PKI. I have set some authentication in the settings (for admin ans HTTP in/Dashboard) 

I'll try to give you some log with a working and a not working version soon .

Best regards

**Comment by TotallyInformation** [comment]
There really shouldn't be any difference since it is the Express server that is being used. This is created by Node-RED and used for the admin ui, Dashboard, HTTP nodes, etc. so if they work, uibuilder should work.

Please share the start of the Node-RED log so we can see what versions of everything you are using and how things are installed. Also, turn on the uibuilder back-end debug and share the resulting uibuilder.log file and finally check in your browser's dev console for any errors (also check the network panel in the browser dev tools to see if anything is not connecting.

**Comment by kazsharp** [comment]
Hi.
I had same issue.
When my browser has no cookie (eg. private window in FireFox, secret window in Chrome), websocket wasn't connected.
I reloaded my browser, thne websocket was connected.
The code of "uibuilder.js" at line 136, it seems to be error that the browser has no cookie.

Regards

**Comment by TotallyInformation** [comment]
Ah, what version of uibuilder and uibuilderfe are you using?

Use the command `uibuilder.get('version')` from the browser console to get the FE version. 

This was changed in later versions firstly to replace cookie use then to reintroduce it with a more robust process with a fallback. This was because sometimes, cookies are not delivered. But cookies are again used as the primary way to communicate the socket channel id to allow for multi-page use.

**Comment by kazsharp** [comment]
Hello. 

The version of uibuilder is "1.0.2"
and ```uibuilder.get('version')``` shows "1.0.0"

Thanks

**Comment by TotallyInformation** [comment]
OK, for some reason you have the old version of the front end.

Ah, just worked out why! I forgot to repack! So `uibuilderfe.min.js` is actually the old version and `uibuilder.js` is the new one - sorry about that.

Can you then switch to the non-minified version until I can update?

**Comment by TotallyInformation** [comment]
v1.0.4 is now released and has matching versions for the FE code. Please update and let me know if you are still having a problem.

**Comment by kazsharp** [comment]
Hi.
I updated node-red-contrib-uibuilder then it worked.

Thank you!

**Comment by Allam76** [comment]
I have the same issue. I'm on 1.0.6. No errors..

**Comment by TotallyInformation** [comment]
Which console? There is the Node-RED log and the console log in the front end. You can also turn on front and back-end debugging separately in order to get more information. Try debugging the front-end first (change the flag in the node's admin panel). See if you are getting any connection errors.

**Comment by Allam76** [comment]
console on front end. Activated front-end debugging. No connection errors or network errors but still ```Websocket State: false```

**Comment by Allam76** [comment]
OK I see, I'm supposed to have a green light underneath the node. Instead I have the blue light with text "node initialized" which I imagine is the socket server not starting. Can't see anything in the log though.

**Comment by Allam76** [comment]
Strange, using the moon example works great.

**Comment by TotallyInformation** [comment]
Yes, the blue light indicates that Socket.IO is ready and listening. A gree light indicates at least 1 client connected, it should show a count of the number of connected clients too.

OK, so if the moon example works, that indicates you may have outdated code in your default example. Try renaming the files - the node will put them back if you make a small change to the node and re-deploy.
