### ISSUE TITLE
Node is not working

### ISSUE THREAD

**Issue by thabjeel** [TotallyInformation/node-red-contrib-uibuilder#25]
I've installed the node, and added it to the flow.  And tried to access the webpage at http://localhost:1880/uibuilder

But I got "Cannot GET /uibuilde" in the webpage.
And in the Debug tab of the nodered got the error "TypeError: root path must be a string".
Need help
![captsure](https://user-images.githubusercontent.com/17821623/33165299-4fb0ad46-d05c-11e7-9abb-42fbfbd00b60.PNG)
![capture4](https://user-images.githubusercontent.com/17821623/33165300-4fe8791a-d05c-11e7-9545-64f303da98ae.PNG)

**Comment by TotallyInformation** [comment]
The answer is in the error message I think. You have an error in the root path. e.g. the URL in the nodes configuration.

Can you give a screenshot of the config?

Also check whether you have changed any Node-RED settings that affect the root URL.

**Comment by thabjeel** [comment]
Thanks for the reply :)

I'm attaching the configuration screenshot. And I didn't change any node red settings. Where should I check that whether it is changed or not?

**Comment by TotallyInformation** [comment]
OK, so the URL looks correct and it doesn't look as though you've changed any of the NR settings - See the part at the bottom that shows you some URL's? Those are clickable. Can you click on the top one - the Base URL? It should take you to the right page.

Can you also please post the Node-RED log from when you start it? Should look something like:

```
0|red      | 24 Nov 09:01:22 - [info] User directory : \Users\test\.node-red
0|red      | 24 Nov 09:01:22 - [info] Flows file     : \Users\test\.node-red\flows_test.json
0|red      | 24 Nov 09:01:22 - [info] Server now running at http://127.0.0.1:1880/red/
0|red      | 24 Nov 09:01:22 - [info] Starting flows
0|red      | 24 Nov 09:01:22 - [info] UI Builder - Version 1.0.2 started at /uibuilder
0|red      | 24 Nov 09:01:22 - [info] UI Builder - Local file overrides at \Users\test\.node-red\uibuilder\uibuilder
0|red      | 24 Nov 09:01:22 - [info] UI Builder - Version 1.0.2 started at /moon
0|red      | 24 Nov 09:01:22 - [info] UI Builder - Local file overrides at \Users\test\.node-red\uibuilder\moon
0|red      | 24 Nov 09:01:22 - [info] UI Builder - Version 1.0.2 started at /moon-status
0|red      | 24 Nov 09:01:22 - [info] UI Builder - Local file overrides at \Users\test\.node-red\uibuilder\moon-status
0|red      | 24 Nov 09:01:22 - [info] UI Builder - Version 1.0.2 started at /uibuilder2
0|red      | 24 Nov 09:01:22 - [info] UI Builder - Local file overrides at \Users\test\.node-red\uibuilder\uibuilder2
0|red      | 24 Nov 09:01:22 - [info] Started flows
0|red      | 24 Nov 09:01:22 - [info] [udp in:1970f2ba.39423d] udp listener at 0.0.0.0:8094
0|red      | 24 Nov 09:01:22 - [info] [mqtt-broker:f26337a5.6f16e8] Connected to broker: JK-SP4-NR@mqtt://192.168.2.2:1883
```

Notice the uibuilder entries that show you both the URL and the physical filing system location of the served files? Make sure those folders exist and contain the expected files (see the README for the details).

**Comment by thabjeel** [comment]
24 Nov 15:18:08 - [info] Node-RED version: v0.17.5
24 Nov 15:18:08 - [info] Node.js  version: v6.11.3
24 Nov 15:18:08 - [info] Windows_NT 10.0.16299 x64 LE
24 Nov 15:18:09 - [info] Loading palette nodes
24 Nov 15:18:12 - [info] Dashboard version 2.6.2 started at /ui
24 Nov 15:18:13 - [warn] ------------------------------------------------------
24 Nov 15:18:13 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
24 Nov 15:18:13 - [warn] [tail] Not currently supported on Windows.
24 Nov 15:18:13 - [warn] ------------------------------------------------------
24 Nov 15:18:13 - [info] Settings file  : \Users\m\.node-red\settings.js
24 Nov 15:18:13 - [info] User directory : \Users\m\.node-red
24 Nov 15:18:13 - [info] Flows file     : \Users\m\.node-red\flows_TJ17AA058-PC.json
24 Nov 15:18:13 - [info] Server now running at http://127.0.0.1:1880/
24 Nov 15:18:13 - [info] Starting flows
24 Nov 15:18:13 - [info] [OpcUa-Browser:80d849b7.6c84c8] start browse client on opc.tcp://opcua.demo-this.com:51210/UA/SampleServer
24 Nov 15:18:13 - [info] [OpcUa-Browser:f3ec331c.13676] start browse client on opc.tcp://opcua.demo-this.com:51210/UA/SampleServer
24 Nov 15:18:13 - [error] [uibuilder:d6b0099f.981978] TypeError: root path must be a string

**Comment by TotallyInformation** [comment]
OK, so this is something not seen by me or others. So a few things to try.

Firstly, could you please install the version from GitHub rather than npm? That is version 1.0.2.

If that doesn't work, could you please turn on the back-end debugging - see the info in README for what you need to add to your settings.js file. That will get you a uibuilder.log file which hopefully will indicate where in the process things are going wrong.

**Comment by colinl** [comment]
Could it be the fact that @thabjeel is not using the usual folder for running node-red (m.node-red rather than .node-red)?

**Comment by TotallyInformation** [comment]
Argh! Good spot Colin.

Yes, there appears to be something seriously wrong with that installation. @thabjeel - you should have a folder underneath the home folder of the user that is running node-red. It is generally named `.node-red` and all of the settings and installed nodes should be within it. If you have an incorrect setup, the node will not find the resources in the correct place as it has to assume that the folder structure matches the one defined in detail in the documentation (the readme file).

Please go back and check that you have Node-RED correctly installed. We've recently updated the documentation for installing and running Node-RED under Windows so now would be a good time to go back and check the docs.

**Comment by thabjeel** [comment]
![capture10](https://user-images.githubusercontent.com/17821623/33251837-da73f734-d35f-11e7-8ccf-27cd93fe288f.PNG)

sorry for the late reply...
I've installed the UI-builder module this way.. is that fine?

**Comment by TotallyInformation** [comment]
Well as you can see, there is an update to 1.0.1 - there is a slightly later version on GitHub but it is fairly small which is why I've not published another update to npm yet.  Certainly run the update you see there.

However, I think that Colin may have spotted the issue, there is something odd with your installation of Node-RED - uibuilder has to know about various folders and those all relate to your `userDir` folder (see the Node-RED installation docs for the meaning of that). On Windows, your userDir - for a standard installation will be in the HOME folder of the user running Node-RED in a sub-folder called `.node-red`.

So in your case (as it appears that the user account running Node-RED is called `m.node-red`) the folder holding the files delivered by uibuilder should be:

    \Users\m.node-red\.node-red\uibuilder\uibuilder\src\

And the folder that contains settings.js (see your startup log) should be:

    \Users\m.node-red\.node-red\

But it isn't, it is in:

    \Users\m.node-red\

**Comment by taw-pi** [comment]
Hi I have a similar problem :-( 

After installing uibuilder following the instructions in Getting Started. The directory 
<user>/.node-red/uibuilder is not created and when I deploy the example flow i get the following error in the flow debug tab...

TypeError: Cannot read property 'middleware' of undefined

simarly

[error] [uibuilder:ede9b0dc.bb67d] TypeError: Cannot read property 'middleware' of undefined

on the node-red console.

I am running on Mac OSX 10.13.2

Installation...

npm install node-red-contrib-uibuilder --save

> uws@0.14.5 install <User>/.node-red/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.

+ node-red-contrib-uibuilder@1.0.4
added 84 packages in 38.311s

Node-Red Console

Welcome to Node-RED
===================

2 Jan 11:56:22 - [info] Node-RED version: v0.17.5
2 Jan 11:56:22 - [info] Node.js  version: v9.3.0
2 Jan 11:56:22 - [info] Darwin 17.3.0 x64 LE
2 Jan 11:56:22 - [info] Loading palette nodes
2 Jan 11:56:38 - [info] Dashboard version 2.7.0 started at /ui
2 Jan 11:56:38 - [warn] ------------------------------------------------------
2 Jan 11:56:38 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
2 Jan 11:56:38 - [warn] ------------------------------------------------------
2 Jan 11:56:38 - [info] Settings file  :<USER>/.node-red/settings.js
2 Jan 11:56:38 - [info] User directory : /<USER>/.node-red
2 Jan 11:56:38 - [info] Flows file     : <USER>/.node-red/flows_<USER>.local.json
2 Jan 11:56:38 - [info] Server now running at http://127.0.0.1:1880/
2 Jan 11:56:38 - [info] Starting flows
2 Jan 11:56:38 - [info] Started flows
2 Jan 11:56:38 - [info] [mqtt-broker:5bb08973.ca9518] Connected to broker: mqtt://raspberrypi-vpn:1883
2 Jan 11:57:50 - [info] Stopping flows
2 Jan 11:57:50 - [info] [mqtt-broker:5bb08973.ca9518] Disconnected from broker: mqtt://raspberrypi-vpn:1883
2 Jan 11:57:50 - [info] Stopped flows
2 Jan 11:57:50 - [info] Starting flows
2 Jan 11:57:50 - [error] [uibuilder:ede9b0dc.bb67d] TypeError: Cannot read property 'middleware' of undefined
2 Jan 11:57:50 - [info] Started flows
2 Jan 11:57:50 - [info] [mqtt-broker:5bb08973.ca9518] Connected to broker: mqtt://raspberrypi-vpn:1883
2 Jan 11:59:39 - [info] Stopping flows
2 Jan 11:59:39 - [info] [mqtt-broker:5bb08973.ca9518] Disconnected from broker: mqtt://raspberrypi-vpn:1883
2 Jan 11:59:39 - [info] Stopped flows
2 Jan 11:59:39 - [info] Starting flows
2 Jan 11:59:39 - [error] [uibuilder:ede9b0dc.bb67d] TypeError: Cannot read property 'middleware' of undefined
2 Jan 11:59:39 - [info] Started flows
2 Jan 11:59:39 - [info] [mqtt-broker:5bb08973.ca9518] Connected to broker: mqtt://raspberrypi-vpn:1883
2 Jan 12:03:21 - [info] Stopping flows
2 Jan 12:03:21 - [info] [mqtt-broker:5bb08973.ca9518] Disconnected from broker: mqtt://raspberrypi-vpn:1883
2 Jan 12:03:21 - [info] Stopped flows
2 Jan 12:03:21 - [info] Starting flows
2 Jan 12:03:21 - [error] [uibuilder:ede9b0dc.bb67d] TypeError: Cannot read property 'middleware' of undefined
2 Jan 12:03:21 - [info] Started flows
2 Jan 12:03:21 - [info] [mqtt-broker:5bb08973.ca9518] Connected to broker: mqtt://raspberrypi-vpn:1883
2 Jan 12:24:45 - [info] Stopping flows
2 Jan 12:24:45 - [info] [mqtt-broker:5bb08973.ca9518] Disconnected from broker: mqtt://raspberrypi-vpn:1883
2 Jan 12:24:45 - [info] Stopped flows
2 Jan 12:24:45 - [info] Starting flows
2 Jan 12:24:45 - [error] [uibuilder:ede9b0dc.bb67d] TypeError: Cannot read property 'middleware' of undefined
2 Jan 12:24:45 - [info] Started flows
2 Jan 12:24:45 - [info] [mqtt-broker:5bb08973.ca9518] Connected to broker: mqtt://raspberrypi-vpn:1883

Hope you can help
Thanks Terry

**Comment by colinl** [comment]
Again it seems that you have an unusual installation, though whether this can cause the middleware error I don't know.  Usually the .node-red folder should be under a user not under /

**Comment by taw-pi** [comment]
My .node-red folder is under a user I edited the post to remove my username for security, although I guess it is a little misleading, sorry.

**Comment by TotallyInformation** [comment]
So to recap. You have Node-RED installed such that your userDir folder is `<user>/.node-red` and you installed uibuilder into that folder? BTW, it is best to install from the Node-RED admin interface as that will always go into the correct folder.

Then you restarted Node-RED and you get the errors above?

Could you please adjust the settings for uibuilder that go into settings.js and set the debug level to `true`? After restarting Node-RED, you should have a log file `<user>/.node-red/uibuilder.log`. Could you please let me have a copy of that? It shouldn't contain anything sensitive except your user home folder which you can change to `<USER>` to make it clear that you've changed it. Thanks.

**Comment by TotallyInformation** [comment]
BTW, you seem to have a problem with your MQTT configuration. You've probably copied the same MQTT client name to 2 different clients.

**Comment by taw-pi** [comment]
Attached as requested..
[uibuilder.log](https://github.com/TotallyInformation/node-red-contrib-uibuilder/files/1600275/uibuilder.log)

BTW I needed to set the default debug flag in uibuilder.js to 'true' to get the file?
There was no obvious way of settings a debug flag  in ~/.node-red/settings.js !

**Comment by TotallyInformation** [comment]
If you read the instructions, it tells you how to set the flag in settings.js

https://github.com/TotallyInformation/node-red-contrib-uibuilder#19-uibuilder-settingsjs-configuration

**Comment by TotallyInformation** [comment]
Hmm, annoyingly, I don't have the version number of the uibuilder instance from the logs - I must correct that, normally that is output early on.

Could you please confirm the version number of uibuilder you have installed?

**Comment by taw-pi** [comment]
I trust this is what you need...
"_id": "node-red-contrib-uibuilder@1.0.4",

It is true that the instructions talk about settings.conf but in my instance there is no 'uibuilder' section in ~/.node-red/settings.conf, perhaps that is the problem? I assume that installing uibuilder would create the appropriate entry in ~/.node-red/settings.conf so perhaps I have not installed it correctly ??

**Comment by TotallyInformation** [comment]
Hi, thanks for being patient. No, the uibuilder section in settings.js is _supposed_ to be optional. Also, it is bad practice for nodes to change the settings.js file since that may also contain security configuration.

Please add the uibuilder section without the middleware part first to see if that is the problem. If not, add a middleware section, you don't need the console.log statement, only the next().

If that is the problem, I thought I'd fixed that so please double check that you have the right version of the uibuilderfe.js file by opening your browser console (F12) and typing in `uibuilder.get('version')`. It should be 1.0.4 as above.

**Comment by taw-pi** [comment]
Problem solved it seems...

I added the uibuilder section to settings.json manually, and set then debug to 'silly', the resulting file is attached...
[uibuilder.log](https://github.com/TotallyInformation/node-red-contrib-uibuilder/files/1600489/uibuilder.log)

At least now I have uibuilder fallback master page. :-)

As a newbie I clearly assumed wrong about nodes updating settings.conf. I am not sure that is clear from the documentation but I guess I could have missed it.

**Comment by TotallyInformation** [comment]
In fact, I've just tested that you don't need either in settings.js, it works fine both without a uibuilder section at all and with the uibuilder section but without the middleware section - on my Windows 10 development PC running latest Node-RED, Node.JS v6.11.3 and uibuilder 1.0.4

**Comment by TotallyInformation** [comment]
Hmm, this is annoying as I still don't think we've got to the bottom of why some people are seeing this error and not others. As I've said and tested, it should work without the settings & does on my PC.

**Comment by taw-pi** [comment]
I have edited my settings.conf as follows...

    uibuilder: {
        // List of npm modules to be made available to any uibuilder instance.
        //   The modules MUST be manually installed at present.
        // userVendorPackages: ['riot', 'moonjs', 'slim-js', 'ractive', 'picnic', 'accounting', 'date-format-lite'],
        // Controls the amount of debug output to ~/.node-red/uibuilder.js
        debug: 'error',  // error, warn, info, verbose, debug, silly; true = silly, false = none
        // Provides an ExpressJS middleware hook. This can be used for custom authentication/authorisation
        //   or anything else you like. If NOT provided, uibuilder instances will also check if
        //   httpNodeMiddleware available.
        // @see https://expressjs.com/en/guide/using-middleware.html
        //middleware: function(req,res,next) {
        //    console.log('I am run whenever a web request is made to ANY of the uibuilder instances')
        //    next()
        //}
    },

... and I do not get any failures.

3 Jan 14:11:23 - [info] 

Welcome to Node-RED
===================

3 Jan 14:11:23 - [info] Node-RED version: v0.17.5
3 Jan 14:11:23 - [info] Node.js  version: v9.3.0
3 Jan 14:11:23 - [info] Darwin 17.3.0 x64 LE
3 Jan 14:11:24 - [info] Loading palette nodes
3 Jan 14:11:25 - [info] Dashboard version 2.7.0 started at /ui
3 Jan 14:11:25 - [warn] ------------------------------------------------------
3 Jan 14:11:25 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
3 Jan 14:11:25 - [warn] ------------------------------------------------------
3 Jan 14:11:25 - [info] Settings file  : <USER>/.node-red/settings.js
3 Jan 14:11:25 - [info] User directory : <USER>/.node-red
3 Jan 14:11:25 - [info] Flows file     : /<USER>/.node-red/flows_Terences-MacBook-Pro.local.json
3 Jan 14:11:25 - [info] Server now running at http://127.0.0.1:1880/
3 Jan 14:11:25 - [info] Starting flows
3 Jan 14:11:25 - [info] UI Builder - Version 1.0.4 started at /uibuilder
3 Jan 14:11:25 - [info] UI Builder - Local file overrides at <USER>/.node-red/uibuilder/uibuilder
3 Jan 14:11:25 - [info] Started flows
3 Jan 14:11:25 - [info] [mqtt-broker:5bb08973.ca9518] Connected to broker: mqtt://raspberrypi-vpn:1883


so I guess as a minimum on MacOSX the uibuilder section is required in settings.json.

**Comment by TotallyInformation** [comment]
OK, thanks for this. I will try to think what might cause that. If you get any thoughts, please let me know. In the meanwhile, I'm going to close this issue now.

**Comment by srebling** [comment]
I am experiencing the same problem as thabjeel on MacOSX. Works fine on Windows10. Here is the end of the node-red start up log:

8 Apr 21:11:54 - [info] Starting flows
info: UIbuilder: Adding master vendor path url=/uibuilder/vendor/normalize.css, path=-1
8 Apr 21:11:54 - [error] [uibuilder:45a9a037.3793d] TypeError: root path must be a string
8 Apr 21:11:54 - [info] Started flows

I think the problem is with the 'path=-1'. The Win10 system log shows the correct path to normalize.ss and jquery in the node_modules dir. Why would it not set the path properly on OSX?

**Comment by ellieejlee** [comment]
Hi I had the same problem and I have a solution - it's node-red user directory related.

I had started a flow + ui-builder components in the default **/Users/.node-red** directory. When I created a new flow with new ui-builder components, the front-end files were still being served from my **/Users/Ellie/.node-red** directory instead of the new directory **/Users/Ellie/Desktop/newfolder**. 

To solve this, I navigated to the new directory and changed the user directory using the command line - "node-red -u ."

**Comment by TotallyInformation** [comment]
Hi Ellie, thanks for reporting.

I think that what you are seeing is expected? Node-RED will always use the default userDir location unless it is pointed elsewhere. That would seem to indicate that the other users were also using non-standard installations but were failing to change the userDir folder. That would make sense.

Personally, I never install Node-RED to the default location. I always install to a folder and create a data dir below that which I then use as the userDir.

In my package.json in the Node-RED install dir, I then use the following script definitions:

```json
  "scripts": {
    "start": "node node_modules/node-red/red.js --userDir ./data",
    "update": "npm install --unsafe-perm node-red",
    "check": "npm outdated",
    "check-data": "cd data && npm outdated",
    "update-data": "cd data && npm update",
    "check-master": "npm outdated",
    "update-master": "npm update",
    "log": "sudo journalctl -u nrlive -f -n 0 -o cat"
  },
```

So that I don't have to think about the parameters.

I have things installed this way both on my Windows dev PC and my 2 Pi's.

As everything uses relative paths, this works no matter where I install things. I can even move everything and as long as I keep that folder structure, it will all continue to work.

I don't like the default installation of Node-RED. While it is simpler for beginners, I think that it causes lots of issues in the longer run. Using global installs is problem enough, especially with security issues. But the lack of control and knowledge over where things are located and the inability to run multiple, parallel instances of Node-RED mean that it really isn't a good idea in my opinion.

Installing Node-RED into a folder with the userDir in a sub-folder. Coupled with some simple package.json files means that everything is neat and tidy, understandable and controllable. It is also very easy to update everything.

Thanks again for this info, hopefully this clears everything up that is related to these issues. Thanks again for the PR as well. I've not had much time to spend on uibuilder recently so the change was welcome indeed. If you are looking for a challenge and have some time, I'd still like to create a set of standard widgets that could be triggered by pre-defined msgs which I think would be a more efficient method than the current Dashboard widget arrangement.
