### ISSUE TITLE
In Windows "Open instance code in VSCode" does not actually open the instance folder

### ISSUE THREAD

**Issue by qxJsc** [TotallyInformation/node-red-contrib-uibuilder#294]
### Current Behavior

When selecting the VSCode icon or link to server folder displayed in the configration dialog of the uibuilder node, VSCode opens but shows no content beside the "Welcome" tab, if activated.

This is likely caused by the backslashes in the 

### Expected Behavior

When selecting the VSCode icon or link, VSCode should open the server instance folder for this uibuilder node.

This is likely caused by the use of backslashes in the URL:
- Only opens empty VSCode
vscode://file\Users\XXXXX\.node-red\projects\myproject\uibuilder/uibtest/?windowId=_blank

- Opens the server instance folder
vscode://file/Users/XXXXX/.node-red/projects/myproject/uibuilder/uibtest/?windowId=_blank

### Steps To Reproduce

1. Open configuratio dialog of the uibuilder node
2. Either click on VSCode icon or select link to server instance

### Example Node-RED flow

```
[{"id":"e5e7d58e.cc132","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"4623170b129b20da","type":"inject","z":"e5e7d58e.cc132","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":340,"y":340,"wires":[["e7666999ee4328a3"]]},{"id":"e7666999ee4328a3","type":"uibuilder","z":"e5e7d58e.cc132","name":"","topic":"","url":"uibtest","okToGo":true,"fwdInMessages":false,"allowScripts":false,"allowStyles":false,"copyIndex":true,"templateFolder":"iife-blank-client","extTemplate":"","showfolder":false,"reload":false,"sourceFolder":"src","deployedVersion":"6.8.2","showMsgUib":false,"title":"","descr":"","x":560,"y":340,"wires":[["ab77c58c0f30186e"],["ce4e0c993316a802"]]},{"id":"ab77c58c0f30186e","type":"debug","z":"e5e7d58e.cc132","name":"debug 1","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":780,"y":320,"wires":[]},{"id":"ce4e0c993316a802","type":"debug","z":"e5e7d58e.cc132","name":"debug 2","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":780,"y":360,"wires":[]}]
```
Inject -> uibuilder -> debug

### Environment

- UIBUILDER version: 6.8.2
- Node-RED version: 3.1.3
- Node.js version: 20.10.0
- npm version: 10.2.5
- Platform/OS: Windows 10
- Browser: Firefox 122.0.1 / Chrome

How is Node-RED installed? (globally/locally? admin/user?):
globally, with admin user

How/where is UIBUILDER installed (palette-manager/globally/locally? Which folder?)
globally

Have you changed any of the `uibuilder` settings in your `settings.js` file?
No

**Comment by TotallyInformation** [comment]
Hi, many thanks for reporting this and including the comprehensive information.

Oddly enough, I've just been working on the code behind this for a feature improvement in the upcoming version of UIBUILDER. In the new version, the link will be exposed as an editable field on the Advanced tab. The setup for uibuilder will attempt to guess not only the local edit path but also a remote one (using the VSCode remote SSH extension) but you will be able to edit the link to your exact requirements. (the remote link is unlikely to work without a tweak due to the complexity of remote logins).

As part of this, I did spot some bugs in the code. They are now fixed as well. However, I've been using a version with that old code on Windows 10 and 11 for quite some time and it has been working for me. So not entirely certain what has gone wrong for you. Anyway, I can see from playing with a vscode link in vscode that it doesn't indeed like the back-slashes but regardless, this is fixed in the dev branch.

The fixes are currently in the v6.9.0 branch on GitHub and if you want to try them, you are welcome to reinstall uibuilder direct from GH. I do try to keep the GH repo branches as working versions though it is possible there might sometimes be some oddities or things that change before release so they aren't recommended for live use.

Can you live with the issue until the new version is released (likely to be another month yet)? Or do you need me to try for a bug-fix release?

**Comment by qxJsc** [comment]
Thanks for the quick response, it not critical or urgent for me, just something I encountered while going through the tutorial.

> However, I've been using a version with that old code on Windows 10 and 11 for quite some time and it has been working for me. So not entirely certain what has gone wrong for you. 
Interesting, it is entirely possible that I have some messed up Windows/browser settings or janky node modules. Since the problem occured on two different hosts, my first conclusion was a bug. But the two hosts do have similar environments.

I'll reinstall uibuilder from the 6.9.0 branch next time I work on it and try it out. 
Thank you for your work & time.

**Comment by TotallyInformation** [comment]
No problem. I'll close this issue. If it becomes more of a problem, please feel free to raise a new issue.

Certainly this area is improved for the next release.
