### ISSUE TITLE
installFolder is an absolute path which depends on the node red project path

### ISSUE THREAD

**Issue by nandlab** [TotallyInformation/node-red-contrib-uibuilder#321]
### Current Behavior

When I clone my Node-RED project on another machine with a different `.node-red` path, the `uibuilder.packages.vue.installFolder` property changes in the `package.json` of uibuilder creating an unnecessary diff in the version control of the project.

### Expected Behavior

It would be better if the `installFolder` property was a local path relative to the uibuilder directory. That way cloning a Node-RED project on another system would not directly modify a file.

### Steps To Reproduce

1. Create a Node-RED project
2. Install uibuilder
3. Install vue framework in uibuilder
4. Commit changes
5. Push project to a remote git repository
6. Clone the Node-RED project on another system

### Environment

- UIBUILDER version: 6.5.0
- Node-RED version: 3.0.2
- Node.js version: v18.19.0
- npm version: 9.2.0
- Platform/OS: Devuan GNU/Linux 5 (daedalus) x86_64
- Browser: Ungoogled Chromium 122.0.6261.128

How is Node-RED installed? Globally with npm.

How/where is UIBUILDER installed? Installed in `~/.node-red/node_modules/node-red-contrib-uibuilder` using palette manager.

Have you changed any of the `uibuilder` settings in your `settings.js` file? No.

`package.json` in uibuilder:
```
{
  "name": "uib-root",
  "version": "6.5.0",
  "dependencies": {
    "vue": "^3.3.4"
  },
  "uibuilder": {
    "packages": {
      "vue": {
        "spec": "^3.3.4",
        "installFolder": "/home/dan/.node-red/projects/node-red-escape-room-controller/uibuilder/node_modules/vue",
        "installedVersion": "3.3.4",
        "estimatedEntryPoint": "dist/vue.global.js",
        "homepage": "https://github.com/vuejs/core/tree/main/packages/vue#readme",
        "packageUrl": "/vue",
        "url": "../uibuilder/vendor/vue/dist/vue.global.js",
        "installedFrom": "npm",
        "outdated": {
          "current": "3.3.4",
          "wanted": "3.3.4",
          "latest": "3.4.21"
        }
      }
    }
  }
}
```

**Comment by TotallyInformation** [comment]
Hmm, interesting. The absolute path is actually a consequence of using Node.js's `join` function to ensure safe, cross-platform file paths. If it were to be made into a path relative to the `uibRoot` folder, when you copied to a new location, it still wouldn't work because you wouldn't actually have those packages installed (in `<uibRoot>/node_modules/`) and you would still have to install them.

In fact, what should really happen is that uibuilder should check whether its packages actually exist when Node-RED starts - in fact, I thought it did. And if they don't exist, it should warn you and empty the list.

**Comment by TotallyInformation** [comment]
OK, so your issue sent me down a load of rabbit holes! 😁

That was good though because that part of the code really did need an update (or 20).

This has resulted in extensive reworking of the package management code for v7 and hopefully the removal of a number of edge-case bugs.

What it hasn't - yet - done is fix your direct issue.

However, what I have done is to make sure that any discrepancies between what is actually installed in `<uibRoot>/node_modules/` and `<uibRoot>/package.json` is highlighted as a warning in the Node-RED log and also in the debug panel. So at least you will know that something needs to be done.

That warning will appear on startup but also whenever you install or remove a library via the uibuilder library manager tab.

On the backlog for a future release are some thoughts about automating the process of fixing discrepancies. This might have unintended consequences however, so more thought is required before I implement something.

---

PS: The `<uibRoot>/package.json` file is updated by several processes in uibuilder since the most common use-case is for people to be managing installations using the library manager tab.

Clearly, in your case, you don't perhaps want people to do this. In your specific case, the best workaround would be to move the uibRoot folder to a common location - perhaps one that is just read-only to Node-RED - you can do that in settings.js under the uibuilder section. Then, because you have a common location and because you are using Linux, the filing system name of the folder won't change.

**Comment by nandlab** [comment]
Thank you for working on this! It would be very convenient, if the uibuilder `node_modules` can be somehow reinstalled when cloning the Node-RED project on a new machine.
