### ISSUE TITLE
Tie-in uibuilder into Node-RED's project feature (one git repo)

### ISSUE THREAD

**Issue by Thomseeen** [TotallyInformation/node-red-contrib-uibuilder#44]
Node-RED offers a convenient project feature (https://nodered.org/docs/user-guide/projects/) to generate a git repository from Node-RED flows. It would be awesome if the uibuilder source files could be integrated into that repository someway. Of course it is possible to initiate a repository doing that manually (that's what I'm doing at the moment) but having uibuilder tied into the project repo automatically would be great!

The project feature creates a new folder structure in the `.node-red` directory `\projects\<projectname>\` where the repository is initialized. That means the possiblity to move the uibuilder folder to that location would already enable a "tie-in".

**Comment by TotallyInformation** [comment]
Hi Thomas, many thanks for raising this. Good suggestion. I don't use projects but I did start thinking about this a while back. Other priorities got in the way.

The only issue is that location handling inside uibuilder is already quite complex - it could really do with some re-factoring to simplify it I suspect.

I don't suppose you would consider doing a pull request?

I'm about to try and deploy v1.1 which introduces source file editing from within Node-RED so if you are able to consider a PR, you should do it against v1.1.

**Comment by Thomseeen** [comment]
I'm practically a total JS-beginner and have never worked with anything "web" but I might have a look into it the next week depending on how busy I will be at work.
I guess the perfect implementation would mimic what Node-Red does. You would still have the `<userDir>/.node-red/uibuilder` direction (for those used to that...) if you are working without a project and also have `<userDir>/.node-red/projects/<projectname>/uibuilder` direction if you are working with a project (so it's one the project level where node-Red inits the git repo).

**Comment by TotallyInformation** [comment]
OK, I've added something to the top of my [to do list](https://github.com/TotallyInformation/node-red-contrib-uibuilder/wiki/To-Do) that should help. Namely replacing all of the references to the location with a single variable.

By the way references to `<userDir>` mean the Node-RED userDir setting which normally points to `~/.node-red`. So the locations would be `~/.node-red/uibuilder/` and `~/.node-red/projects/uibuilder/`.

I'm also planning to enhance the new `uibindex` (v1.1.0 just published) admin API endpoint so that it can return more information including the actual folder containing the files for the instance.

**Comment by TotallyInformation** [comment]
Complete in v2 as mentioned in the PR.
