### ISSUE TITLE
Problem save file from ace editor in frontend with adminAuth enable

### ISSUE THREAD

**Issue by ElGranLoky** [TotallyInformation/node-red-contrib-uibuilder#51]
### Software and Package Versions

Software       | Install | Version
-------------- | ------- | -------
Node-RED       |  Docker | v0.20.3
uibuilder node |  dashboard admin | 1.2.1
Node.js | - | v8.15.1

Linux 4.4.0-127-generic x64 LE

If you enable adminAuth the POST in uibuilder fails with 401 error. Without adminAuth work as expected. 

![Error save file uibuilder from web - ace editor](https://user-images.githubusercontent.com/2712200/54813509-ff5e9880-4c8d-11e9-96a9-b8de5f90d414.png)

**Comment by TotallyInformation** [comment]
Ooh, good catch, thanks for reporting. I've clearly missed something important there. I will try to track that down. I expect that v2 has the same issue.

**Comment by TotallyInformation** [comment]
Fixed in v1.2.2, please keep an eye out for it. I will try to publish today but I have to go out in a while. If not, I will publish tomorrow. Pick up from GitHub master branch if you are desperate. Also fixed in the v2 branch and already posted so you can try that if you like. Just note the minor breaking changes.

**Comment by TotallyInformation** [comment]
OK, v1.2.2 published. Hopefully that fixes it.
