### ISSUE TITLE
How do we use .allowScript?

### ISSUE THREAD

**Issue by Lung4444** [TotallyInformation/node-red-contrib-uibuilder#54]

**Comment by TotallyInformation** [comment]
Hi, the pro-former content in the body of the issue is there to help ensure that I can help you by understanding your issue better. 

In this case, it looks like you are asking a question rather than raising an issue. I can answer here but it is often better to use the Node-RED Discourse forum for questions as others from the community are better able to also help.

To use, you have to enable it in the settings for your uibuilder node. Once enabled, you can add JavaScript code to a msg property `msg.script` as mentioned in the help and docs.

You don't need to wrap the code in `<script>` tags or anything else, just pass the code as a string and it will be interpreted in the browser by appending it to the on-page scripts. 

You can also change the `uibuilder.allowScript` setting in your front-end code. That enables/disables the uibuilder front-end library to insert an incoming `msg.script` property to the DOM dynamically. This is done for you if you tick the option in the node settings.

Note that only a single set of code will be added. So if you resend a msg with `msg.script`, that will entirely replace any existing code.

This is really a bit of a hangover from the early days of uibuilder. Obviously, it is generally better to write code in `index.js` (or your own file that you load to the browser) that will handle any data you send. Sending dynamic code clearly has some dangers.

Hope this explains things sufficiently?

**Comment by Lung4444** [comment]
It work.
I send the script for the update of the keyframe rule when it receive the data from the meter of a audio device.

Thanks
