### ISSUE TITLE
[Request] bare minimum examples

### ISSUE THREAD

**Issue by bakman2** [TotallyInformation/node-red-contrib-uibuilder#57]
The examples included and in the wiki have 300+ lines of code. 
Perhaps an idea to just show (or include) the bare minimum how to send and receive messages. 

Currently I have to dig through the code and weed out the stuff I don't need and remove functions that are used to demonstrate some increment/message button, which requires reverse engineering.

eg. include this .js and initialize vue/js/etc like this, send/receive like this and nothing more.

**Comment by TotallyInformation** [comment]
Great point. In fact, there should be one that requires no framework at all. I will see if I can produce one or two examples that do the absolute minimum.

I have a day off on Friday to try and finish off v2 so I'll try to get this done as well.

The default template code that comes with uibuilder is designed to show a range of interactions so that people can see things working right out of the box. While it is a little more complex, the code is well documented and should help anyone get going quickly. So I probably won't be changing that though if you have any thoughts on something slightly different that still illustrates the interaction between VueJS and uibuilder, please do let me know.

**Comment by bakman2** [comment]
It is just when I look through the included example, I am presented with:
```
 data: {
        startMsg    : 'Vue has started, waiting for messages',
        feVersion   : '',
        counterBtn  : 0,
        inputText   : null,
        inputChkBox : false,
        socketConnectedState : false,
        serverTimeOffset     : '[unknown]',
        imgProps             : { width: 75, height: 75 },

        msgRecvd    : '[Nothing]',
        msgsReceived: 0,
        msgCtrl     : '[Nothing]',
        msgsControl : 0,

        msgSent     : '[Nothing]',
        msgsSent    : 0,
        msgCtrlSent : '[Nothing]',
        msgsCtrlSent: 0,
    }
```
Which of these properties can one remove ? All ? 
Is `data` required and the `methods` part ? 
In the `mounted` part it appears that the 'app' is initialized there. 

But there is a comment: `// Available hooks: init,mounted,updated,destroyed` 

As a noob I would expect the initialisation to happen in the `init`-hook and updates to happen in the `updated`-hook. I don't see the `init` and `updated` (and `destroyed`) coming back in the code, what are they used for ?

**Comment by TotallyInformation** [comment]
Well, a **little** knowledge - at least some background reading - about VueJS is assumed. I've tried to follow decent best-practice.

The `data` section defines variables that are reactive and managed by Vue. So if they are updated, Vue will update the DOM automatically.

If you take them out, you also need to take out their references in the HTML.

Computed provides dynamic data, again they relate to the UI so check out their use in the HTML. For example, the `hLastRcvd` actually calls the `syntaxHighlight` method - actually I could simplify that and I probably should. 

The important point about a computed property is that it updates automatically if one of the underlying values used to calculate it is updated. If the underlying values don't change, the property is not recalculated which makes them very efficient.

Methods, on the other hand are just functions that are attached to the Vue instance. They are recalculated each time they are called.

https://stackoverflow.com/a/44350932/1309986

---

In regard to the hooks, there is no need to use the updated hook at all in this case since Vue itself is doing all the heavy lifting and recalculating things on update of data or computed properties. Init is used to tee everything up.

In addition, we make use of uibuilder's own event system to trigger updates to the Vue data properties. Again, no need to worry about Vue's own updates, it takes care of it itself.

```
Node-RED sends msg to websocket -> uibuilderfe's websocket receives the msg
 -> uibuilderfe triggers an event on the uibuilder.msg object
 -> the event handler updates the Vue `msgRecvd` data variable.
```
[The event handler definition](https://github.com/TotallyInformation/node-red-contrib-uibuilder/blob/v2/nodes/templates/vue/index.js#L131)

Computed property `hLastRcvd` ([html](https://github.com/TotallyInformation/node-red-contrib-uibuilder/blob/1db4f75796cf64950f3198ca082baca9aa183194/nodes\templates\vue\index.html#L103-L104), [definition](https://github.com/TotallyInformation/node-red-contrib-uibuilder/blob/1db4f75796cf64950f3198ca082baca9aa183194/nodes\templates\vue\index.js#L47-L48)) references the Vue `msgRecvd` data variable and so is automatically recalculated when that changes. That change updates the UI with a syntax highlighted version of the new json data.

[Here is a decent explanation of the VueJS processing lifecycle](https://alligator.io/vuejs/component-lifecycle/). Don't worry, it took me a few goes to understand it. 

The best thing to do is to work through some examples from the web so you get a feel for it.

The reasons I've swapped to Vue from jQuery as the default template are:

* VueJS is actually easier to use to create dynamic, data-driven interfaces that jQuery
* VueJS is smaller and lighter than jQuery
* VueJS is vastly more powerful and useful for writing data-driven user interfaces
* VueJS is massively well supported and is the fastest growing front-end framework

vue-bootstrap isn't totally necessary but with it, you don't really have to do any CSS design since bootstrap has all the basics already in place.

---

One thing that you've done is to make me think again about the template as it now stands and what information you get about it. So I will try to add some more in-line help and I'll try to move some of this to the WIKI and create a reference in the template code so that others can get more help if they need it.

In the meantime, please let me know if there is anything else you would like to understand about how the template works.

Also, don't forget that the other templates should still be good if you want to use a different framework. If you have a favourite framework that I've not yet covered, please consider doing a basic example and posting to the WIKI.

Thanks for your contribution, it is being very helpful.

**Comment by bakman2** [comment]
Thanks for the detailed information. "Totally information" ;)

I cleaned up and reverse engineered most of the basics and have some interaction working. 
I can see the use of Vue vs jquery it is a different framework, jquery by itself has become somewhat redundant with lots of functionality already available with ES6. 

>The data section defines variables that are reactive and managed by Vue. So if they are updated, Vue will update the DOM automatically.

This is a point that introduces some problems for me. The wiki explains caching and refers to a caching-node for node-red. The code for this node is no longer there. Then I read about an alternative via a function node. This part assumes that everything arrives via mqtt (?) for me it doesn't, data could come from anywhere.

Some thoughts: 

Store the `data` variables (last state) in a file, so upon reload of the page they can be loaded, and going further: 

Create the variables on the fly as the script asks for it, this would eliminate doing the doublework defining the variables (not sure if this is possible). 

Example:
```
data: {
		msgsReceived: ['Unknown'],
		msgsSent: ['Unknown'],
		temperature_indoor: '',
		co2: '',
		humidity_indoor: '',
		noise: '',
		pressure: '',
	}

...

uibuilder.onChange('msg', function(v) {
			console.log(v);
			if (v.topic == 'netatmo') {
				d.co2 = v.payload.dashboard_data.CO2;
				d.humidity_indoor = v.payload.dashboard_data.Temperature;
				d.temperature_indoor = v.payload.dashboard_data.Humidity;
				d.noise = v.payload.dashboard_data.Noise;
				d.pressure = v.payload.dashboard_data.Pressure;
			}
		});
```
This is mqtt data (with an stored object).
All these properties also have to be defined in `data`, unless I am missing something.

**Comment by TotallyInformation** [comment]
Sorry about the delayed response. Real life getting in the way! :(

> This is a point that introduces some problems for me. The wiki explains caching and refers to a caching-node for node-red. The code for this node is no longer there. Then I read about an alternative via a function node. This part assumes that everything arrives via mqtt (?) for me it doesn't, data could come from anywhere.

It really doesn't matter where the data comes from as long as you are sending it to the node. You can use the cache function node to keep track of incoming data within Node-RED and the control output messages will inform the flow when a new client connects or when an existing client reloads the page. In either of those cases, the example function will resend the cached data.

Apologies that I never got around to writing an actual cache node, I always intended to but there are too many other competing calls on my time to say nothing of distracting myself with new projects. However, the function node version does work and has the advantage that you can tweak it if it doesn't quite do what you want. If you think of anything you think it should do, let me know and I'll see if I can update it.

> Store the data variables (last state) in a file, so upon reload of the page they can be loaded, and going further:

It is much better to control this from Node-RED not from the front-end. So you aren't really interested in what is in data other than ensuring that any of the front-end data variables are populated from incoming messages from Node-RED. 

If you want to retain the last user inputs as well, you would add an `onchange` method to the html element that caused a `uibuilder.send()` function call to send that data back to Node-RED as well, then add that to the cache. 

Just note that Node-RED tracks the client usage by the socket ID. This _does_ change on page reload so it isn't really reliable if you need to track multiple clients. You would need to ensure that you have some other form of user identification that you send in the message payload. You may then need to tweak the cache function to store/replay data by user

The cache function node example simply stores into Node-RED's global variable store. You could, of course, use the filestore version of that so that data is retained even on restart. So you don't actually need to change the function code other than to use the filestore name in the `get` and `set` functions. You set the filestore up in the settings.js file for Node-RED. Node-RED's docs cover that.

You could also use a file out to do the same thing. For example, you could add another output to the function node and link that to the file save node.

> Create the variables on the fly as the script asks for it, this would eliminate doing the doublework defining the variables (not sure if this is possible)

No, this is a limitation of VueJS and many other similar frameworks. That is because tracking changes and unknown number of dynamically, late created variables is quite inefficient.

You can, of course create JavaScript variables dynamically but then you wouldn't get the benefit of Vue's extremely efficient update handling. 

You could also create them dynamically and then add `watch` functions. [This post](https://codingexplained.com/coding/front-end/vue-js/adding-removing-watchers-dynamically) provides some ideas about adding watchers dynamically. If you really need to do this, I would probably create an empty Object variable in `data` and append properties to it dynamically then add a watch accordingly.

As you can appreciate, this is a more advanced use-case for something like VueJS and many other frameworks. There are various other ways of achieving this that I can think of but they are all quite involved. It is better to rethink your approach or use a different framework. If you really want a totally dynamic page, you might be better off using jQuery or similar but just be aware of the performance overheads. This might not matter if your page is fairly small.

> All these properties also have to be defined in data, unless I am missing something.

No, you could tweak that somewhat to reduce the amount of variables to something more manageable. 

Here is an example page that I have created using uibuilder:

![image](https://user-images.githubusercontent.com/1591850/62007746-3287cb80-b149-11e9-8250-aa77b56653e2.png)

It uses 3 Vue "components" to help break down the complexity. The main Vue object has this data defined:

```
new Vue({
    el: "#app",
    // We don't really need a function here but you do in components - keeping things consistent
    data: function() { return {
        // For formatting dates and times
        dtOpts: {
            timeZone: 'Europe/London',
            weekday: 'short', month: 'short', day: 'numeric',
            hour: 'numeric', minute: 'numeric',
        },
        dtFmt: 'en-GB',
        // Which tab should be active?
        tabIndex: 0,
        // heating
        lastUpdate  : '[None]',
        hTimer      : null,
        showNoUpdAlert    : false,
        demand            : undefined,
        percentageDemand  : undefined,
        demandOnOffOutput : 'N/A',
        demandMax         : 100,
        isBoosted         : false,
        homeData          : [],
        // Field definitions - @see https://bootstrap-vue.js.org/docs/components/table#field-definition-reference
        homeDataFields    : [
            {   key: 'floor',
                label: 'Floor',
                sortable: true,
                class: 'border-right text-center',
                thStyle: {width: '2em !important'},
            },
            ...
        ],
        // Current Switch Settings
        switches: {},
        // Current Device statuses
        devices: {},
    }}, // --- End of data --- //
```

Notice how the `homeData` array is empty.

And here is the uibuilder.onchange function that populates things from incoming messages:

```
        // Save confusion by keeping a specific reference to this Vue app
        const vueApp = this

        uibuilder.onChange('msg', function(newVal){
            //console.debug('Vue:mounted:UIBUILDER: property msg changed! ', newVal)
            vueApp.msgRecvd = newVal

            // What kind of message did we receive?
            // Use getProp so we don't pollute the original input. Then tidy the topic
            let topic = getProp(newVal, 'topic').replace(/\/SWITCH..$/,'')
            if ( topic.substring(0,8) === 'DEVICES/' ) topic = 'DEVICES'
            switch (topic) {
                // Full homeDetails
                case 'Home Details':
                    // for convenience
                    const data = newVal.payload

                    // Formatted last update
                    vueApp.lastUpdate = vueApp.fmtTime(data.lastUpdate)

                    // clear and restart countdown. If lastUpdate not updated in 2 minutes, show a warning.
                    vueApp.showNoUpdAlert = false; clearInterval(vueApp.hTimer); vueApp.hTimer = null;
                    vueApp.hTimer = vueApp.heatingUpdTimer()

                    vueApp.demand  = data.demand
                    // for convenience ...
                    vueApp.percentageDemand  = data.demand.PercentageDemand
                    vueApp.demandOnOffOutput = data.demand.DemandOnOffOutput
                    vueApp.isBoosted        = data.demand.isBoosted
                    break

                // Individual switch update
                case 'COMMAND':
                    //console.debug('UIBUILDER:onChange:msg: COMMAND/SWITCHnn msg received ', newVal)
                    let sw = newVal.topic.replace('COMMAND/','')
                    vueApp.switches[sw].status = newVal.payload
                    break

                // Full switch update
                case 'SWITCHES':
                    vueApp.switches = newVal.payload
                    break

                // Individual device update
                case 'DEVICES':
                    //console.debug('UIBUILDER:onChange:msg: DEVICES/+ msg received ', newVal)
                    let dev = newVal.topic.replace('DEVICES/','')
                    vueApp.devices[dev].status = newVal.payload
                    break

                // Full devices update
                case 'DEVICESFULL':
                    vueApp.devices = newVal.payload
                    break

                // Don't process default
                default:
                    //ignore
            }
        }) // ---- End of uibuilder.onChange() watcher function ---- //
```

Notice how this splits things up by topic. In particular, the "Home Details" topic contains a **mass** of data in a single payload object.

Updating an array defined in `data` triggers Vue's update cycle. Updating a property deep inside an Object doesn't.

Hope this gives you some more ideas?

If you want to see the full code, it is available [here](https://github.com/TotallyInformation/node-red-contrib-uibuilder/wiki/Examples-Vue-Complex-Home-Dashboard)

**Comment by TotallyInformation** [comment]
OK, for now I am going to close this issue. I have created a WIKI page to help people discover this conversation and I will continue to expand it as time allows.

By the way, the WIKI is open for editing so please feel free to improve it and add comments as you like.

https://github.com/TotallyInformation/node-red-contrib-uibuilder/wiki/Getting-Started-with-VueJS

**Comment by boisei0** [comment]
@TotallyInformation Julian, the example you linked for the home dashboard has the full Javascript listed for both the HTML and JavaScript headers. The HTML with the templates is missing.

**Comment by TotallyInformation** [comment]
Oops! It will be fixed in 10 minutes. Thanks for letting me know.

**Comment by TotallyInformation** [comment]
Hi, if anyone is still tracking this, please see the new chart examples in the WIKI as they are typically MUCH simpler than the default template.

**Comment by bakman2** [comment]
Sorry for the late reply @TotallyInformation, it is bit of information overload for me, the "bare minimum" examples would be an example of sending/receiving and the replay method, combined with a flow. The replay still confuses me, in NR i see `cacheControl: "REPLAY"`, what should one do with this, connect as a trigger and loop it back into uibuilder ?

In the apex charts example (this is a nice library, I use it in other projects), there is another comment that confuses me:
```
  /** **REQUIRED** Start uibuilder comms with Node-RED @since v2.0.0-dev3
         * Pass the namespace and ioPath variables if hosting page is not in the instance root folder
         * e.g. If you get continual `uibuilderfe:ioSetup: SOCKET CONNECT ERROR` error messages.
         * e.g. uibuilder.start('/nr/uib', '/nr/uibuilder/vendor/socket.io') // change to use your paths/names
         */
```
What does this mean ?

**Comment by TotallyInformation** [comment]
My turn to apologise now since I missed this as I was preparing to go on hols. In the end had to take my laptop anyway so here I am catching up.

Isn't this flow sufficient?

https://github.com/TotallyInformation/node-red-contrib-uibuilder/wiki/Cache-and-Replay-Messages-without-using-node-red-contrib-infocache

I think that I may have also included that in the examples?

Basically, you will find that whenever a client (which might just be a new browser tab) loads in the browser, it triggers a connect message and a cache replay msg. You can use the cache replay msg to do just that, feed it back upstream to your caching function to get it to release the cache back to the originating client - it only goes to the specific client that just asked for it.

This also happens if you reload the page, that has the same effect as a new connection since you've just deliberately reloaded everything, losing any browser data in the process.

This caters for things like dynamic charts where you can send back an amount of data when a page reloads or a new client connects. Unlike Dashboard, this is optional since that isn't always the effect you may want - sometimes you might always want a clean start.

Is that clearer?

**Comment by bakman2** [comment]
@TotallyInformation I have the "cache" working to replay messages, I get the gist of it thanks. My dashboard is coming along with a bunch of template components en interactions between them, it took some brainwaves to understand what is going on, but the sky is clearing.

I created a [gist with a minimal example](https://gist.github.com/bakman2/8e8232f144c7ac34d4dbbd08cd9fc97b) for myself as I would use/present it, reducing the noise and keeping it focussed. The documentation in the wiki confuses/overwhelms to be honest (not as much anymore, but resort to vue documentation now). Additional elements/interactions would either require the knowledge and/or documentation anyway.

**Comment by TotallyInformation** [comment]
Cool, I'll have a look when I get back from hols. Always good to get a fresh view and I'm always looking for ways to improve the docs and examples.

**Comment by TotallyInformation** [comment]
Haha, well that is certainly minimal!

I will add an example like this to the WIKI and probably to the built-in examples as well so that people get a feel for the range of options.

It turns out that the GitHub WIKI really isn't that helpful a tool once you get beyond a simple set of pages. I need to redo the WIKI as a proper documentation site.

I've already started to work through setting up GitHub pages instead though the content is blank at the moment.

https://totallyinformation.github.io/node-red-contrib-uibuilder/

Ultimately though, it might end up as a separate Hugo site as I already use Hugo for several other sites.

**Comment by boisei0** [comment]
Would you like PRs on that documentation pages?

**Comment by TotallyInformation** [comment]
If it is a WIKI page, you can just go ahead and make a change, just let me know so that I can review it later.

For the docs folder that presents the github pages view, I think I'll hold off because I don't really want to burden the main repo with loads of docs files that will never get used in situ, only via the web. I think it will be better to create a new site.

For now, if you have any thoughts or content you think should be in the docs, feel free to create new WIKI pages so we have everything in one place. Any site I create will use Markdown anyway. As soon as I have more time, I'll then start to reorganise things.

I will also add you as a contributor to uibuilder.

**Comment by TotallyInformation** [comment]
I've created a flow based loosely on your example.

I have added a bit to it so that it becomes something practical that people can use but without (hopefully) making the front-end code too complex to understand.

https://github.com/TotallyInformation/node-red-contrib-uibuilder/wiki/Simple-example

Actually points to an entry on the Flows site since I thought it good to have another avenue of discoverability. I will add it to the examples in a future release.

https://flows.nodered.org/flow/bbe6803d9daebda5c991336cf4e5e3e0

I think that it is a really nice example. It shows how to generate a "Quote of the day" page very easily using a really simple Node-RED flow and even simpler front-end code.

**Comment by bakman2** [comment]
@TotallyInformation correct me if i'm wrong, but when loading that flow example and looking at the `index.js` comment, that is jquery ?

**Comment by TotallyInformation** [comment]
Argh! I forgot to paste back the code 👎 

Thanks, I will fix asap.

**Comment by TotallyInformation** [comment]
Now updated.
