### ISSUE TITLE
Help implementation

### ISSUE THREAD

**Issue by robertowiest** [TotallyInformation/node-red-contrib-uibuilder#66]
Hello, how are you? I need to implement a somewhat complex multi-sensor monitoring system connected via MQTT. And I also need a login control system. How could I use ui-builder to implement these features?

**Comment by TotallyInformation** [comment]
You are generally best connecting to MQTT via Node-RED and passing data as needed into a uibuilder node. similarly, data returning from your front-end page(s) will be received by the uibuilder node and can be further processed and/or sent out to to MQTT.

It is also possible to use a front-end library to talk to MQTT directly if you need to however. You can use uibuilder to install an npm package and it will be added to the web server so that you can add it to your front-end code in the same way as you do for socket.io/vue/etc.

For login and authorisation, you will need to do a couple of things for maximum security.

1. Use the middleware feature of uibuilder. This lets you add code to a file that uibuilder will load then execute every time a user (re)loads an http connection associated to your uibuilder node. You can find the type of coding to use by researching security middleware for ExpressJS.

2. You also will most likely want to secure your websocket connection. uibuilder also provides a middleware capability for that too. However, securing websockets is a little more complex as the middleware is only called when the socket is first connected (which uses http). The socket then "upgrades" to a websocket connection that doesn't support custom headers and so you have to do further checking by attaching data to all of the data you send back to uibuilder. I will be adding some standards later on but this work isn't started yet I'm afraid. Until then, you will need to manage the data yourself. 

---

For example, your http middleware might redirect to a login page if the users browser session isn't authenticated. That would set up a JWT authorisation header (and hopefully record some basic details like last seen date/time and source IP address so that you can continue to validate the connection). The JWT header is returned to the browser and it will send it back every time the user reloads.

You would also then copy the token and attach it to all messages you are sending back to Node-RED and you would add a small flow that replicated the token checks.

Your checks would ensure that the token is valid (you can unencrypt it), that the session hasn't timed out (JWT sessions generally have to be short but can be renewed on each connection from the client) and that the data is still being received from the same IP address (to help mitigate token hijack attacks).

This represents a simple authentication and authorisation setup. None of this is really specific to uibuilder. What uibuilder does is to facilitate the presentation of front-end libraries and presents a dedicated websocket connection. 

It also provides some control messages on output port 2 that lets you take actions when a new client connects (or a user reloads). That can facilitate some caching in Node-RED that will ensure that new/updated client connections receive recent data if you need that.

**Comment by robertowiest** [comment]
Very good. I see that creating this authentication process is not so simple. If you had any usage examples it would be easier to understand and implement.

**Comment by TotallyInformation** [comment]
You are correct and it is on my todo list I'm afraid.

I also forgot to mention that any login processing absolutely needs TLS so you need to know how to get Node-RED to use HTTPS instead of HTTP. That is the place to start since you will need that before you can go further.

There is information on this on the Node-RED documentation site.

Honestly, when you are doing this, using NGINX or HAproxy is **much** easier than messing with Node-RED. There are various articles around on how to do it, it isn't that hard to do.

---

You can see though why many of us bypass this all together and use something like Telegram instead. While this doesn't give you such a rich interface, it does allow you to create a secure conversational interface that is more than good enough for issuing simple commands and getting back some simple info.

For example, I have commands that give me a summary of temperature, humidity and lights status around the house. I can also turn on and off lights.

**Comment by TotallyInformation** [comment]
I'm going to close this issue for now if you don't mind. I've got the subject on my backlog and will work on it as time permits.

For a robust security setup though, I would probably generally opt to use something more industrial than Node-RED. So you may wish to look at using NGINX (or other web server) as a reverse proxy and to terminate the authentication process there.

After that, it is more a case of just using the middleware function to check for a valid header on incoming requests.
