### ISSUE TITLE
Installing "@scope/package" front-end library through uibuilder manager fails

### ISSUE THREAD

**Issue by boisei0** [TotallyInformation/node-red-contrib-uibuilder#69]
Continuing this from Slack last night:
I'm trying to install a front-end library through the library manager in the node. Goal is to have the library served through express so the parts can be used in the frontend code. 

With NR settings to trace log level, and enabling a log file with the npm install, the following lines get written to the log:
```
26 Sep 19:58:25 - [info] [uibuilder/uibnpmmanage] Admin API. Running npm install for package @syncfusion/ej2-vue-schedule
26 Sep 19:58:52 - [trace] [uibuilder/uibnpmmanage] Writing stdout to /home/pi/.node-red/uibuilder/home/pi/.node-red/uibuilder/.config/npm-out-latest.txt
26 Sep 19:58:52 - [error] [uibuilder/uibnpmmanage] Admin API. npm command failed. npm install for package @syncfusion/ej2-vue-schedule
```
Since I was just uncommenting debug code, I didn't care about the path in there, but if this ever is turned into an option it will need a bit of work :) Gets written to the correct path though.

[npm-out-latest.txt](https://github.com/TotallyInformation/node-red-contrib-uibuilder/files/3662034/npm-out-latest.txt)

However, manually running the code described in the relevant files, will have no failures in installing, _and_ will have `require.resolve()` find the correct path. 

```
pi@neela:~/.node-red $ node
> const path = require('path')
undefined
> const fs = require('fs-extra')
undefined
> require.resolve('@syncfusion/ej2-vue-schedule', {paths: ['/home/pi/.node-red/']})
'/home/pi/.node-red/node_modules/@syncfusion/ej2-vue-schedule/dist/ej2-vue-schedule.umd.min.js'
> path.dirname(require.resolve('@syncfusion/ej2-vue-schedule', {paths: ['/home/pi/.node-red/']}))
'/home/pi/.node-red/node_modules/@syncfusion/ej2-vue-schedule/dist'
> 
```

```
pi@neela:~/.node-red $ npm install --no-audit --no-update-notifier --save --production --color=false --json @syncfusion/ej2-vue-schedule
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN @syncfusion/ej2-vue-base@17.2.47 requires a peer of vue@2.5.2 - 2.5.21 but none is installed. You must install peer dependencies yourself.
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.

{
  "added": [
    {
      "action": "add",
      "name": "@syncfusion/ej2-file-utils",
      "version": "17.2.47",
      "path": "/home/pi/.node-red/node_modules/@syncfusion/ej2-file-utils"
    },
    {
      "action": "add",
      "name": "@syncfusion/ej2-compression",
      "version": "17.2.47",
      "path": "/home/pi/.node-red/node_modules/@syncfusion/ej2-compression"
    },
    ... // see the attached file for an exact copy
}
```

### Software and Package Versions

Software       | Version
-------------- | -------
Node.JS        | 10.16.0
npm            | 6.9.0
Node-RED       | 0.20.8
uibuilder node | 2.0.3
uibuilderFE    | 2.0.2
OS             | Raspbian Stretch on Pi3B+
Browser        | Firefox 69.0.1 on MacOS Mojave 10.14.6

**Comment by TotallyInformation** [comment]
OK, I think I've found at least one problem with trying to use Syncfusion. When you try to install `@syncfusion/ej2-vue-schedule`, it goes on and installs **17** packages!

If you look in the dev console in your browser when adding the package, you will see the details:

![image|643x499,75%](upload://7O1HlqTpJVl1nsUB42Mv8wBndpK.png) 

There is quite a large issue here. Currently, uibuilder makes the assumption that an installation delivers a single folder in `node_modules`. So having 17 show up means that this wont work even if it recognised the installation.

1) The package name you are installing is **NOT** the package that is installed.
2) Even if I deal with that, I then need to add the actual 17 packages.

Honestly, this is a nightmare.

While I can conceive of some possible approaches to dealing with this, it isn't going to be quick or easy.

There are currently two work-arounds that I can thing of:

1) Include the packages from the `unpkg` CDN (or similar) which is what I think you've done.
2) Install the packages into the Node-RED static folder or the uibuilder common folder so that they are served up by the `serveStatic` function. This would mean that _everything_ in the respective folders is available - possibly including files that really shouldn't be available so this might be a security issue.

I will add this as an enhancement for a future release and if you'd like to work on it, the processing would need to go into the `findPackage()` function in the `tilib.js` file. However, I'm also about to move that file to a different npm package so that it can be referenced from multiple nodes. 

https://github.com/TotallyInformation/TI-Common

**Comment by boisei0** [comment]
I have  a workaround to just use a local install plus build step for development, then upload the dist versions to the device instead. Works fine for me, but it was something I stumbled upon in attempting to go the direct way through the node. I agree with the nightmare aspect, it's the same when writing code for it, and eslint complains for all the right reasons that you need to add a whole bunch of other packages to your `packages.json` file for development. I'd even go as far and state that it's a problem with Syncfusion libraries in general, after working with them for a while. While there is native vue support this way, it's not great in terms of Vue core principles like reactivity and I'm adding workarounds for that to my components. 

I do not know if this issue is specific to @scope/package libraries, or to libraries that like syncfusion install a bunch of sublibraries along with itself that it depend on everywhere...

**Comment by TotallyInformation** [comment]
I have found another issue which may also be a little tricky to deal with and that is that my workaround #3 above doesn't work because `findPackage` expects to find a simple package name and it doesn't cope with @ scoped names which are installed in a sub-folder.

I think that this is a bit more of an important one than this issue and I will raise a different issue for it.

While probably not that urgent to fix, it will need fixing at some point.

I'm afraid that I'm going to close this issue - however, it is referenced in the [To Do](https://github.com/TotallyInformation/node-red-contrib-uibuilder/wiki/To-Do) entry in the WIKI.

**Comment by TotallyInformation** [comment]
Thanks Lena for your updates, I've added "I have a workaround to just use a local install plus build step for development" as workaround number 4 and made it the recommended approach for now.

As there are 3 viable workarounds, I'm going to close this issue now since it is unlikely to actually get an enhancement any time soon. Sorry.  :-(

**Comment by boisei0** [comment]
Understandable, perfect for me, just something that's good to be aware of. And now that it's known and documented on the TODO list, others potentially running into the same issue can find out too.
