### ISSUE TITLE
How to run UIBuilder through XAMPP for local scripts

### ISSUE THREAD

**Issue by juliusdeblaaij** [TotallyInformation/node-red-contrib-uibuilder#77]
Hello,
I am trying to run UIBuilder through XAMPP,
as I need to run a javascript file (Artyom.js, speech recognition wrapper), which I cannot because in the regular port chrome won't allow running File:///

Can anyone guide me to info, or explain to me, the right approach?

### Software and Package Versions

Software       | Version
-------------- | -------
Node.JS        | 9.0.0
npm            | 5.5.1
Node-RED       | 1.0.1
uibuilder node | ? possibly also 2.0.5 
uibuilderFE    | 2.0.5
OS             |  Win10 1903
Browser        | Versie 77.0.3865.120 (Officiële build) (64-bits)

### How is Node-RED installed? Where is uibuilder installed?
C:\Users\juliu\.node-red

UIBuilder config, common, uibuilder:'
C:\Users\juliu\.node-red\uibuilder

UIBuilder module:
C:\Users\juliu\.node-red\node_modules\node-red-contrib-uibuilder

**Comment by TotallyInformation** [comment]
Hi Julius, quick aside before answering - it would be better for you to be using a non-dev version of node.js, typically odd numbered versions like v9 are development versions. With Node-RED, it is best to try and stick to one of the LTS versions. Currently v8.16 or v10.15. v12 will be LTS next month I think at which point, v8 will drop off.

So your actual issue is that you are trying to access a `file:` url in a page that is served from `http:` and this indeed isn't allowed by any current browser since it is a massive security issue.

But you don't need to do that, why not simply move the `Artyom.js` file into uibuilder's src folder or even into the static folder that Node-RED provides? Then you can call it via the server like everything else?

But even better would be to use uibuilder's library feature to install the `artyom.js` package. Once you've done so, not only can you update it in the same way as all of your other nodes, but uibuilder will serve it up for you on the url: `../uibuilder/vendor/artyom.js/build/artyom.window.js`

Adding that url on a script tag in your index.html file will load it straight into your browser and make it available to your own scripts in index.js.

**Comment by juliusdeblaaij** [comment]
Thank you for a swift and detailed response. 
I have solved it myself, as I finally figured out how to create my own web pages last evening (**I did not know that UIBuilder generates folders for you, this isn't mentioned in the docs (possible suggestion?)**). I am running a script by Artyom for in-window use which works well. So no need for XAMPP right now. Your suggestion on the library feature deserves some looking into if I decide to solidly expand my project.
My problem is solved.

**Comment by TotallyInformation** [comment]
Great, glad you got it working.

> this isn't mentioned in the docs

It is mentioned though perhaps some of the use isn't obvious? 

Whenever you add a new uibuilder instance and deploy, a new folder is created `<uibRoot>/<uibURL>` and in that folder are `src` and `dist` folders. The `src` folder is where your front-end code resides. uibuilder will serve up anything that is included in the src folder (unless there is an index.html file in the dist folder in which case the dist folder is used instead of src - that lets you use a build step).

There is also a `<uibRoot>/common` folder that is always served up to all instances of uibuilder.

All of these are served using Node-RED's user-facing ExpressJS server. 

At the end of the day, uibuilder is the following:

* A web server
* A websocket server
* An editor for front-end code
* An npm package manager for front-end libraries

The web server serves up:

* Your custom front-end code (index.(html | js | css), etc.) - for each instance of the uibuilder node
* The vendor libraries that you installed with the package manager
* Common front-end code

If ever you can't work out what uibuilder is serving up, please **use the advanced information link** that you will find in the settings for any uibuilder node instance. That will launch a page that shows you everything you may wish to know including all of the uibuilder endpoints being served, all of vendor libraries being served, all of the server's folders and all of the relevant URL's and some more stuff that may be useful.
