### ISSUE TITLE
Show detailed information button not functioning

### ISSUE THREAD

**Issue by bakman2** [TotallyInformation/node-red-contrib-uibuilder#78]
### Issue

Clicking the "Show detailed information" button takes me to `http://10.0.0.6:1880/uibindex` and returns `Unauthorized`

### Reproduce

Add a uibuilder node to node-red, click done, deploy.
Doubleclick the uibuilder node again, click the "Show detailed information" button.

### Expected result

Honestly I am not sure what it should display (detailed information?), unauthorized does not sound good.

### Software and Package Versions
Software       | Version
-------------- | -------
Node.JS        | v10.16.3
npm            | 6.11.3
Node-RED       | 1.0.1
uibuilder node | 2.0.5
uibuilderFE    | ?
OS             | MacOs Catalina
Browser        | Safari 13.0.2

**Comment by TotallyInformation** [comment]
No, unauthorised isn't right :-)

You should only get that if you have applied authentication to the Node-RED Editor and the browser window/tab you are using doesn't have access to the token cookie that Node-RED delivers. That is because the API call is secured.

https://github.com/node-red/cookbook.nodered.org/wiki/Create-an-admin-configuration-API-endpoint

https://nodered.org/docs/api/modules/v/0.20.0/@node-red_editor-api_auth.html

So when you click on the link, by definition you should have any required authorisation since you've come from the Editor.

You could try emptying your browser cache, reloading the Editor and trying again. Also check that you haven't done anything odd in your settings.js file in respect to user permissions.

**Comment by TotallyInformation** [comment]
@bakman2 - any update on this?

**Comment by stanleyseow** [comment]
I hv the same issue , login with admin, still get the Unauthorized

my setup are 

Node v12.13.1
npm 6.12.1
node-red 1.0.3
uibuilder node  2.0.6
Ubuntu 18.04.3 LTS
Browser Chrome Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by TotallyInformation** [comment]
Tracking in: https://discourse.nodered.org/t/uibuilder-uibindex-not-working/22116
