### ISSUE TITLE
Using PassportJS with uibuilder

### ISSUE THREAD

**Issue by j2l** [TotallyInformation/node-red-contrib-uibuilder#81]
It's just a follow-up of the TODO. Feel free to close it down as soon as it's read

I desperately need the login (and user CRUD) and noted it"s on the ToDo list, and I wondered if:
https://glitch.com/~webdevsimplified-nodejs-passport-login
could help you finalize it 😸 

I just don't know YET how to adapt a basic nodejs project to uibuilder.
I've seen uibMiddleware but don't get how to adapt to it :(

**Comment by TotallyInformation** [comment]
Thanks for the comment. Finding time is proving challenging.

uibMiddleware is automatically inserted as a function to the ExpressJS server. So wherever you see an example that assigns a function to the Express app, you can use the middleware function. You will note that it has the 3 parameters expected of an Express middleware app. The `req`uest object, the `res`ult object and and the `next` callback function.

The function that is exported will be called _every_ time anyone tries to access any of the pages you define within uibuilder. That means that you currently need to take a slightly different approach than the one in the link you've shared which only works where you have control over the whole node.js server.

You need to try to keep that function as light as possible since it will be called a lot. 

You would probably create a separate login.html file rather than using the `app.get('/login'` from the example. The function would redirect to that if the user does not have a valid credential. `res.redirect('./login.html')` (note the leading dot).

I _think_ that you may be able to put other code outside the module.exports in the uibMiddleware file - possibly that might let you load passport there (you will need to install the passport package of course). However, I've really not had time to work out the best approach for integrating passport as yet.

I'd love to hear from you if you do manage to get further and I'll leave this open for now so please feel free to add info to it - I will change the title though. I will also add anything if I get time to have a go.

**Comment by j2l** [comment]
Thanks for your help @TotallyInformation 
I don't know passport enough to develop it :(
Well, I hope someone will do.

"This message is for you young Jedi"
![image](https://i.imgur.com/XdTwrPo.jpg)

**Comment by TotallyInformation** [comment]
I'm working on it - slowly :)

**Comment by j2l** [comment]
May the force be with you Julian!

**Comment by j2l** [comment]
Any news on this one?
Maybe just checking/getting JWT at login/register should do it?

**Comment by TotallyInformation** [comment]
Hi, I'm still looking. To be honest, setting up JWT with a login isn't that hard. However, that isn't in any useful way, Secure. JWT is a convenience function not a security function.

In addition, JWT doesn't help secure the websocket connection.

The issue with JWT is that it is subject to session hijacking. So the tokens need to be short-lived and you need a secure mechanism for updating the tokens. You cannot easily do that with a single-page app since most of the communications happens over websockets which don't support headers. So you have no way of expiring/renewing the token.

I am trying to work out the best way of supporting a standard method for doing this via websockets. I'm not a professional dev though so it all takes a lot of time.

**Comment by j2l** [comment]
Oh, it's far beyond what I thought.
I'm sure you'll make it happen!

**Comment by TotallyInformation** [comment]
If you want to take part in the discussion about how to achieve this, please note the new forum post:

https://discourse.nodered.org/t/uibuilder-security-proposal/19882

And my current proposal is documented in the WIKI, here:

https://github.com/TotallyInformation/node-red-contrib-uibuilder/wiki/Security-Design-v2

**Comment by TotallyInformation** [comment]
Going to close this for now. Work is ongoing in the `security` branch.

**Comment by Patriciawa** [comment]
Maybe this will work? https://www.npmjs.com/package/express-socket.io-session. It uses cookies to authenticate, not JWT session tokens, as far as I can tell. Here's also an interesting blog post https://yeti.co/blog/token-based-header-authentication-for-websockets-behind-nodejs/

**Comment by j2l** [comment]
Thanks @Patriciawa 
By any chance, do you have the same need of auth in Node-Red+UIBuilder?
Can you share more about your solution?

**Comment by Patriciawa** [comment]
@j2l I'm in the same boat as you, I don't have a well working solution. What I do have is a half working solution, you shouldn't use it since it's pretty insecure, has some bugs, is hard to manage (in my opinion) and requires you to edit the source files, which I'm not a fan of. Take a look here: https://github.com/phyunsj/node-red-dashboard-login/blob/master/README.md

**Comment by j2l** [comment]
Thanks!
We'll do

**Comment by TotallyInformation** [comment]
Hi Both, just to reitterate, anything based on cookies may fail if the client rejects them as may well happen. In addition, like using JWT, the cookie exchange only happens on initial connections and on any polling requests. It does not happen again once the connection has been "upgraded" to websockets. You can see that in action on the network tab of your developer console when on a uibuilder page.

This means that the session cannot be validated once websockets comms has started unless some other mechanism is provided that uses the msg's themselves. It is that that I'm working on in the security branch. Passing a JWT in the msg instead of just the header. Then getting a process in place on the server that checks the JWT but also allows you to add extra processing of your own since JWT's are a convenience mechanism and not a security feature in themselves since they are easily hijacked. JWT's are designed to have short-term lifespan's, seconds to minutes.

Nearly all of the examples of JWT's that you see on the web are very insecure because of this misunderstanding.
