### ISSUE TITLE
Need help using external vue component

### ISSUE THREAD

**Issue by egs2003** [TotallyInformation/node-red-contrib-uibuilder#83]
I want to use the following vue component (https://github.com/silencesys/silentbox). However, I do not know how to do this. 

with the code 

import Vue from 'vue'. 
import VueSilentbox from 'vue-silentbox 

Vue.use(VueSilentbox)

it's not working.

i have already extended the script statement in the index.html for the file index.js with type="module". But it simply does not work

**Comment by TotallyInformation** [comment]
`import` statements are not native to your browser - as yet. So when you see that in example front-end code, you know that the author is expecting you to have a build step using something like webpack.

That would walk through the code and translate it into something that the browser can actually run. In the process, things like imports will also be reflected in your html file so that the resources are correctly loaded.

In the case of silentbox, I can see that they provide an [unpkg ](https://unpkg.com/) link `"unpkg": "dist/vue-silentbox.min.js",` in `package.json`. Unpkg lets you load resources remotely over the Internet - ideal if you want to test a library as it means that you don't have to mess with installing it locally.

The good news is that it seems that, although they don't document it, the library seems to have been packaged for use directly as well. 

So, if you include the following in your `index.html` file after the Vue/bootstrap entries but before your `index.js` entry, it should work - I've not tried it though:

```html
<script src="https://unpkg.com/vue-silentbox@0.1.9/dist/vue-silentbox.min.js"></script>
```

Then in your `index.js` file, you should add the following statement early in the file, before the `var app1 = ...` statement:

```javascript
Vue.use(VueSilentbox)
```

Please let me know if this works or not.

Also, you are likely to get more comprehensive, and often faster, responses if you raise queries like this in the [Node-RED Discourse forum](https://discourse.nodered.org/) since people with greater VueJS experience may well respond.

**Comment by egs2003** [comment]
Did not work
vue.js:634 [Vue warn]: Unknown custom element: <silentbox-single> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by TotallyInformation** [comment]
Then sorry, but it is beyond my VueJS knowledge. I would suggest raising an issue with the author asking them how to load and use the components in the browser without using a build step.

One other thing you can try as long as you are using a modern browser. You could load the ESM version of the library as a module as per this WIKI article.

You will have to replace the link to your index.js file as well in your index.html:

```
    <script type="module" src="https://unpkg.com/vue-silentbox@0.1.9/dist/vue-silentbox.esm.js"></script>
    <script type="module" src="./index.js"></script>
```

Note the use of `type="module"` on each line. Then you can use the `import` statements as given in the library's readme.

Again, not tried this, it should in theory work but who knows.

**Comment by egs2003** [comment]
import VueSilentbox from 'https://unpkg.com/vue-silentbox@0.1.9/dist/vue-silentbox.esm.js'
Vue.use(VueSilentbox)

that works, great

**Comment by TotallyInformation** [comment]
Great, glad to hear it.

On the roadmap for uibuilder is the integration of a build step to make things easier. However, you can still use one before then, the details are in the WIKI. So if you come across something that you can't work through, you may wish to consider setting that up. It is a pain to initially configure but once set up, it is very easy to use.
