### ISSUE TITLE
Uibuilder vue drag and drop builder

### ISSUE THREAD

**Issue by igisho** [TotallyInformation/node-red-contrib-uibuilder#86]
Hi,

thank you for this fantastic node. I just wanted to put into your attention that there is library for drag and droup vue frontend builder. It may be nice addition to your great work. https://github.com/vuegg/vuegg

**Comment by TotallyInformation** [comment]
Many thanks for your kind words. Always nice to get feedback.

I'm aware of several drag/drop libraries for VueJS and one day I'll find time to try one of them and do a write-up for the WIKI.

If you know how to use the one you suggest, please feel free to add a page to the WIKI as an example and let me know so that I can add it to the menu.

I'll close this for now. Thanks again for your input. You can continue to add to this thread even if closed, I will get notifications.
