### ISSUE TITLE
[Feature request] export/backup/restore uibuilder source files

### ISSUE THREAD

**Issue by simonbuehler** [TotallyInformation/node-red-contrib-uibuilder#89]
hi,

what a wonderful piece of software!

one thing thats annoying in the current workflow is that there is no way to export a flow with uibuilder and its js/html/css/... source files when wanting to deploy to another instance. comment nodes are a pain to use, is there any fix or workaround posssible?

thanks!

**Comment by TotallyInformation** [comment]
Hi Simon, many thanks. You've raised a good point and a good feature request.

Of course it isn't easy to do since there is no direct connection between the front-end code and the back-end. As you will see from the examples that are included with uibuilder, I generally create some comment nodes that contain the code that you can copy and paste as needed and that are copied when you copy the flow. So that is the easiest workaround for now.

There is, of course already a feature built into the uibuilder Editor config panel that will get the text for a specific file. But really, what would be needed is an API that zips up the whole folder and makes it available for download. That's because you may well have files that are binary not text (e.g. images) and that wouldn't be able to be put into a flow.

How is your node.js coding? :-) If someone were at least to do the legwork of working out how to write an API that would do that and what dependencies it might have, I could probably slot it into the existing code fairly easily.

If someone were able to work out how to create a new node from an Editor API call, I could even change the editor to add at least the text of the 3 standard index.[html,js,css] files to comment nodes automatically.

Otherwise, this will go onto the [backlog](https://github.com/TotallyInformation/node-red-contrib-uibuilder/wiki/To-Do) I'm afraid and will need to wait until I have some more time available.

**Comment by NoFr1ends** [comment]
Another idea would be an import and export button in the uibuilder node.
This button could than generate a zip file or extract the zip file in the folder.

This would be a workaround which is more or less easy to implement.

**Comment by TotallyInformation** [comment]
That may be doable. I'll add it to the backlog as well. Many thanks for the input.
