### ISSUE TITLE
URL can't be root?

### ISSUE THREAD

**Issue by edorgeville** [TotallyInformation/node-red-contrib-uibuilder#90]
Hi,
Is it possible to have set uibuilder URL to the root?
I already have `httpAdminRoot: '/admin'` in `settings.js`, but the URL property of the node seems to validate the string isn't empty.
`/`  doesn't work either.
Thanks!

(I asked this question on the node-red slack [a month ago](https://node-red.slack.com/archives/C7K77MG06/p1588715566043900), not sure if this was the right place. Posting here as there seems to be more activity 😁 )

**Comment by TotallyInformation** [comment]
Hi Erwan, I don't believe that it will be possible.

This is both because of the way that it is written but also that Node-RED assumes that it can take over everything. 

Of course, it it possible to move Node-RED away from the root URL to make way for other things but uibuilder still needs a unique identifier so that it can cater for multiple instances. Each instance uses the name specified in the config to define not only the URL but also the matching filing system folders.

So that's the bad news. Now the good. 

A work-around for now is to use a reverse proxy. Then you can move things around however you like, hide port numbers, apply different security schemes and so on.

Also, one of the possible enhancements that I've been considering is to have an option to put uibuilder onto its own ExpressJS server that is separate to the ones used by Node-RED. That would give a number of advantages including the ability to control security completely independently to Node-RED itself. This is actually relatively easy to do in the Node-RED framework thanks to Node.js and ExpressJS. More work would still be needed to allow the root URL to be used though.

I will add the requirement for using the root URL to the backlog. Not sure when I'll be able to get to it though. If you feel like a challenge, PR's are most welcome. :-)

**Comment by edorgeville** [comment]
Hi Julian,
Thanks for answering back!
The most efficient way for me will be reverse proxying. Not a big issue as I already had Traefik in front of everything, just need to learn v2 some more.
Thanks again :)

**Comment by TotallyInformation** [comment]
No problem. I'll certainly look into allowing a root url in the future & it is on the todo list in the WIKI.
