### ISSUE TITLE
Removed files are recreated when clicking "edit source files"

### ISSUE THREAD

**Issue by bakman2** [TotallyInformation/node-red-contrib-uibuilder#91]
**Issue:** 
files (index.js/html/manifest etc) are recreated when clicking "edit source files"

**Reproduce:** 

- Drag a uibuilder node in the workflow 
- set a new url
- deploy

```
cd ~./node-red/uibuilder/<newurldir>/src
rm *
```
- doubleclick the uibuilder node, click "edit source files"

```
ls -l 
```
- All deleted files are recreated and back in the src dir

**Comment by TotallyInformation** [comment]
Change the flag that controls that feature :-)

![image](https://user-images.githubusercontent.com/1591850/84433400-1ccaaa00-ac26-11ea-881a-2f4c5b1556d6.png)

**Comment by bakman2** [comment]
Isn’t that strange behavior?

I can understand it for the initial creation but not after it was created.

**Comment by TotallyInformation** [comment]
No, not really because without them you get unexpected results which would be very hard for a non-developer to track down (you get a default page that is contained in the uibuilder source code so not readily accessible). You also wouldn't get any template at all when you first deployed a node which again I think would be very confusing.

A future enhancement on the backlog is to allow selection of a template when creating a new instance, that would be better all round but more complex to program and it isn't top of the priority list I'm afraid. More than happy to take a PR though :hint:. :-)
