### ISSUE TITLE
UIBuilder & node-red projects

### ISSUE THREAD

**Issue by NoFr1ends** [TotallyInformation/node-red-contrib-uibuilder#94]
The uibuilder node seems to have issues with enabled node-red projects.
When switching between two projects which both have a uibuilder node in place the path where the source files are stored are wrong.

For example if I have the following projects:
**projectA** - with uibuilder path /projectA
**projectB** - with uibuilder path /projectB

When I have `projectA` open and switch to `projectB`, uibuilder creates the `projectB` folder inside `projectA/uibuilder` instead of switching to `projectB/uibuilder/projectB`. If I restart node-red after switching the project uibuilder uses the correct project folder.
It seems like uibuilder stores the project path and does not refresh it when the project changes.

node-red version: 1.1.2
uibuilder version: 2.0.8
nodejs version: 12.18.2

**Comment by TotallyInformation** [comment]
Hmm, good spot. Personally, I don't use projects due to having encountered a number of issues and experienced data loss in the past. So I have limited experience with it.

Usually, you can assume that any Node-RED setting is static and can only change when Node-RED is restarted. Clearly Node-RED doesn't actually restart when you change projects which would have been helpful. That means that the path to the uibRoot folder will change dynamically which uibuilder certainly cannot cope with.

I wonder if Node-RED outputs any kind of event when a project switches? I will check with Nick and Dave to see if anything is available. I'm not sure what can be done if Node-RED doesn't provide some kind of event as I don't think there will be any way to detect and respond to the change.

**Comment by NoFr1ends** [comment]
A quick scroll through the source of node-red lead me to this:
https://github.com/node-red/node-red/blob/a9d1a64c32a0a933c2b257498aaaefc83c7e4462/packages/node_modules/%40node-red/runtime/lib/storage/localfilesystem/projects/index.js#L355

As far as I understand the node-red source this should emit an event when the project get reloaded (which is the case when changing the project).
It get triggered multiple times when changing a project tho, but I think it could be possible to check if the path has changed than and if so reinitialize the needed uibuilder variables.

**Comment by knolleary** [comment]
That's right @NoFr1ends - `runtime-event` event can be listened to on the `RED.events` object. It gets triggered lots of different ways, but the key thing to look for is the `action` property of the event payload - it will have the value `"loaded"`

```
RED.events.on("runtime-event", function(payload) {
   if (payload.action === "loaded") {
      // A new project has been loaded
   }
});
```

**Comment by NoFr1ends** [comment]
@knolleary shouldn't the id (project-update) also get checked?

**Comment by TotallyInformation** [comment]
Thanks both, I will see what I can do to include this.

**Comment by NoFr1ends** [comment]
Any update on this?

**Comment by TotallyInformation** [comment]
I'm afraid not. If you wanted to look at the code for uibuilder.js in the security branch to have a look, I think you may find that fixing this may not be so easy since there has been no expectation that uibRoot would change except on restart of Node-RED. Also, I don't currently have a dev install of node-red that has projects turned on.

I would, of course, be more than delighted to take a PR to fix this problem if you have the time to resolve it.

At the moment, I am spending any time I have for uibuilder development on getting the security build ready to merge back to master in readiness for the release of v3. But I have very little time at present.

**Comment by AndreKR** [comment]
I'm still seeing this with uibuilder 6.4.1.

By the way, I'm using [node-red-contrib-projectdir](https://github.com/ianmacs/node-red-contrib-projectdir) to find the current project directory at runtime, maybe you could use the same technique that it is using?

**Comment by TotallyInformation** [comment]
That is correct. As previously mentioned, uibuilder expects its root folder only to change on a restart of node-red. The 2 possible work-arounds right now are:

1) Set the uibuilder root folder to a fixed location. Which can be done in [settings.js](https://totallyinformation.github.io/node-red-contrib-uibuilder/#/uib-configuration?id=settingsjs).
2) After changing projects, restart Node-RED.

I have added a reminder to revisit this issue when time permits. However, this is not a trivial change since uibuilder would have to tear down and rebuild most of its web routes in-flight not just when Node-RED starts.
