### ISSUE TITLE
How to build an executable with ElectronJS

### ISSUE THREAD

**Issue by pmortelette** [TotallyInformation/node-red-contrib-uibuilder#97]
Hi,

I was wondering if this is possible to build an executable with ElectronJS using UIBuilder instead of node-red-dashboard.

I'm actually trying to get everything running but having a lot of issues when I start the application (a lot of 404 errors).

If anybody already make an executable, please explain to me how you did it.

Thanks

**Comment by TotallyInformation** [comment]
Hi, sorry about the delayed response.

You could, I expect, build an executable app with Electron. It would include just your front-end code and possibly a copy of uibuilderfe.js.

You would need to use the optional parameters to `uibuilder.start()` to tell the library where the Node-RED server existed and what the Socket.IO namespace was.

On the roadmap (though a long way off probably unless someone supplies some code) is a web worker variation of the uibuilderfe library which would allow the app to be "installed" on a device. Though of course, since uibuilder is primarily a data-driven web app tool, you would most likely still want to keep the websocket connection live.
